In [2]:
import numpy as np
import pandas as pd
import csv
import json
from sklearn import preprocessing

#### Read csv data into a pandas dataframe

In [3]:
aid = pd.read_csv('aiddata-countries-only.csv', delimiter=',')

In [4]:
aid

,Unnamed: 0,aiddata_id,aiddata_2_id,year,donor,recipient,commitment_amount_usd_constant,coalesced_purpose_code,coalesced_purpose_name
0,1,2.414478e+06,NaN,1977,Saudi Arabia,India,348718518.0,23030,Power generation/renewable sources
1,2,2.414509e+06,NaN,1977,Saudi Arabia,Brazil,191647004.0,23040,Electrical transmission/ distribution
2,3,2.414635e+06,NaN,1983,Saudi Arabia,India,79371799.0,21030,Rail transport
3,4,2.414665e+06,NaN,1984,Saudi Arabia,Taiwan,212202942.0,21030,Rail transport
4,5,2.414667e+06,NaN,1984,Saudi Arabia,Korea,134511154.0,21040,Water transport
5,6,2.414684e+06,NaN,1985,Saudi Arabia,India,128074768.0,23000,"Energy generation and supply, combinations of ..."
6,7,2.414760e+06,NaN,1987,Saudi Arabia,India,72707674.0,21040,Water transport
7,8,2.414840e+06,NaN,1993,Kuwait,Cyprus,25461230.0,21020,Road transport
8,9,2.415076e+06,NaN,1996,Kuwait,Lithuania,21381183.0,23050,Gas distribution
9,10,2.415206e+06,NaN,1998,Kuwait,India,1107033.0,21020,Road transport
10,11,2.426999e+06,NaN,1978,Kuwait,India,103885863.0,23000,"Energy generation and supply, combinations of ..."
11,12,2.427052e+06,NaN,1976,Kuwait,India,193588873.0,23030,Power generation/renewable sources
12,13,2.427058e+06,NaN,1976,Kuwait,Thailand,12905925.0,23040,Electrical transmission/ distribution
13,14,2.427115e+06,NaN,2001,Kuwait,Slovak Republic,1219994.0,14020,Water supply and sanitation - large systems
14,15,2.428296e+06,NaN,1992,Kuwait,Cyprus,6635123.0,21020,Road transport
15,16,2.428502e+06,NaN,1989,Kuwait,India,43493083.0,31320,Fishery development
16,17,2.428506e+06,NaN,1988,Kuwait,Cyprus,16145060.0,21020,Road transport
17,18,2.428566e+06,NaN,1988,Kuwait,Cyprus,27769503.0,14020,Water supply and sanitation - large systems
18,19,2.428587e+06,NaN,1986,Kuwait,Cyprus,30606432.0,21020,Road transport
19,20,2.428601e+06,NaN,1986,Kuwait,India,53561256.0,23030,Power generation/renewable sources
20,21,2.428623e+06,NaN,1984,Kuwait,Cyprus,27051193.0,14040,River development
21,22,2.428652e+06,NaN,1983,Kuwait,India,133092433.0,32220,Mineral/Metal prospection and exploration
22,23,2.428882e+06,NaN,1982,Kuwait,India,131175647.0,32120,Industrial development
23,24,2.428885e+06,NaN,1982,Kuwait,Thailand,50452172.0,23030,Power generation/renewable sources
24,25,2.428888e+06,NaN,1983,Kuwait,Cyprus,21878208.0,21020,Road transport
25,26,2.428969e+06,NaN,1981,Kuwait,India,83971160.0,43010,Multisector aid
26,27,2.428974e+06,NaN,1981,Kuwait,Thailand,65310902.0,23020,Power generation/non-renewable sources
27,28,2.429003e+06,NaN,1981,Kuwait,India,149282062.0,23020,Power generation/non-renewable sources
28,29,2.429034e+06,NaN,1979,Kuwait,Thailand,59307807.0,23000,"Energy generation and supply, combinations of ..."
29,30,2.429037e+06,NaN,1980,Kuwait,Cyprus,23153412.0,14040,River development
...,...,...,...,...,...,...,...,...,...
98510,98511,9.060009e+11,NaN,2013,Portugal,Chile,109.0,16061,Culture and recreation
98511,98512,9.060009e+11,NaN,2013,Poland,Brazil,63571.0,11420,Higher education
98512,98513,9.060009e+11,NaN,2013,Greece,India,24288.0,11420,Higher education
98513,98514,9.060009e+11,NaN,2013,Poland,Brazil,1657.0,11420,Higher education
98514,98515,9.060009e+11,NaN,2013,Poland,Brazil,4141.0,11420,Higher education
98515,98516,9.060009e+11,NaN,2013,Greece,Brazil,25253.0,11420,Higher education
98516,98517,9.060009e+11,NaN,2013,Portugal,Brazil,17651.0,24020,Monetary institutions
98517,98518,9.060009e+11,NaN,2013,Slovak Republic,Chile,2296.0,11420,Higher education
98518,98519,9.060009e+11,NaN,2013,Greece,Chile,1671.0,11420,Higher education
98519,98520,9.060009e+11,NaN,2013,Portugal,Brazil,197649.0,43082,Research/scientific institutions
98520,98521,9.060009e+11,NaN,2013,New Zealand,India,7911.0,11420,Higher education
98521,98522,9.060009e+11,NaN,2013,New Zealand,Brazil,81580.0,24030,Formal sector financial intermediaries
98522,98523,9.060009e+11,NaN,2013,New Zealand,Brazil,52072.0,11420,Higher education
98523,98524,9.060009e+11,NaN,2013,New Zealand,Chile,73769.0,15110,Economic and development policy/planning
98524,98525,9.060009e+11,NaN,2013,New Zealand,South Africa,112232.0,91010,Administrative costs
98525,98526,9.060009e+11,NaN,2013,New Zealand,India,954657.0,16030,Housing policy and administrative management
98526,98527,9.060009e+11,NaN,2013,New Zealand,Chile,245607.0,11420,Higher education
98527,98528,9.060009e+11,NaN,2013,New Zealand,Colombia,244739.0,31100,"Agriculture, combinations of purposes in Agric..."
98528,98529,9.060009e+11,NaN,2013,New Zealand,South Africa,27772.0,11420,Higher education
98529,98530,9.060009e+11,NaN,2013,New Zealand,South Africa,77240.0,15110,Economic and development policy/planning
98530,98531,9.060009e+11,NaN,2013,New Zealand,Thailand,60751.0,11320,Secondary education
98531,98532,9.060009e+11,NaN,2013,Czech Republic,Brazil,4001.0,11320,Secondary education
98532,98533,9.060009e+11,NaN,2013,Czech Republic,Thailand,127.0,15110,Economic and development policy/planning
98533,98534,9.060009e+11,NaN,2013,Czech Republic,Chile,3678.0,15110,Economic and development policy/planning
98534,98535,9.060009e+11,NaN,2013,Czech Republic,South Africa,2382.0,11105,"Education, level unspecified, purpose unspecif..."
98535,98536,9.060009e+11,NaN,2013,Czech Republic,Colombia,51840.0,11420,Higher education
98536,98537,9.060009e+11,NaN,2013,Czech Republic,India,35380.0,72010,Material relief assistance and services
98537,98538,9.060009e+11,NaN,2013,Czech Republic,India,11930.0,11420,Higher education
98538,98539,9.060009e+11,NaN,2013,Czech Republic,Brazil,6669.0,16010,Social/ welfare services
98539,98540,9.060009e+11,NaN,2013,Czech Republic,Chile,7145.0,11120,Education facilities and training

In [5]:
aid.count()

Unnamed: 0                        98540
aiddata_id                        98540
aiddata_2_id                      69695
year                              98540
donor                             98540
recipient                         98540
commitment_amount_usd_constant    98540
coalesced_purpose_code            98540
coalesced_purpose_name            98540
dtype: int64

In [7]:
aid.columns

Index(['Unnamed: 0', 'aiddata_id', 'aiddata_2_id', 'year', 'donor',
       'recipient', 'commitment_amount_usd_constant', 'coalesced_purpose_code',
       'coalesced_purpose_name'],
      dtype='object')

#### Group by donor and recipient respectively

In [8]:
# donor = aid.groupby('donor').sum()[['donor','commitment_amount_usd_constant']]
# recipient = aid.groupby('recipient').sum()[['commitment_amount_usd_constant']]

aid['donated_amount'] = aid['commitment_amount_usd_constant'].groupby(aid['donor']).transform('sum')
aid['recieved_amount'] = aid['commitment_amount_usd_constant'].groupby(aid['recipient']).transform('sum')

# donor = aid[['donor','donor_amount']]
# recipient = aid[['recipient','recipient_amount']]

# donor.drop_duplicates()
# recipient.drop_duplicates()

# res = pd.merge(donor,recipient, left_on='donor', right_on='recipient')
# res.drop_duplicates()

### Mini Project 2: Visualization 1

In [9]:
temp = aid[['year','donor','recipient','commitment_amount_usd_constant','donated_amount','recieved_amount']]
donor = temp.groupby(['year','donor'])[['commitment_amount_usd_constant']].sum()
recipient = temp.groupby(['year','recipient']).sum()[['commitment_amount_usd_constant']]

donor = donor.rename(index=str, columns={"commitment_amount_usd_constant": "donated_amount"}).drop_duplicates()
donor

                      donated_amount
year donor
1973 Australia          4.628586e+07
     Belgium            3.925134e+07
     Canada             4.379284e+08
     France             2.471896e+08
     Germany            5.622324e+08
     Italy              1.667191e+08
     Japan              9.389659e+08
     Netherlands        1.627509e+08
     Norway             3.587485e+07
     Sweden             1.683693e+08
     Switzerland        1.406094e+07
     United Kingdom     4.425792e+08
     United States      1.553264e+09
1974 Australia          2.695088e+07
     Austria            2.412633e+07
     Belgium            4.358860e+07
     Canada             6.850216e+07
     Denmark            5.683929e+07
     France             3.673847e+08
     Germany            6.981681e+08
     Japan              2.730202e+09
     Netherlands        3.234684e+08
     Norway             9.488752e+07
     Sweden             3.029933e+07
     Switzerland        6.454953e+07
     United Kingdom     1.405379e+09
     United States      8.710922e+08
1975 Australia          7.769178e+07
     Belgium            3.886331e+07
     Canada             9.302768e+07
...                              ...
2012 United Kingdom     3.864977e+08
     United States      1.093497e+09
2013 Australia          6.726506e+07
     Austria            7.169039e+06
     Belgium            6.831735e+07
     Canada             5.478420e+07
     Czech Republic     1.231520e+05
     Denmark            4.941770e+06
     Finland            1.393371e+07
     France             1.247092e+09
     Germany            1.582597e+09
     Greece             2.221310e+05
     Iceland            1.334180e+05
     Ireland            1.128518e+07
     Italy              2.367975e+07
     Japan              2.641200e+09
     Korea              3.973233e+08
     Luxembourg         7.645306e+06
     Netherlands        1.105506e+07
     New Zealand        1.938330e+06
     Norway             2.950173e+08
     Poland             4.031840e+05
     Portugal           6.629414e+06
     Slovak Republic    4.114700e+04
     Slovenia           1.430800e+04
     Spain              5.583594e+07
     Sweden             8.227042e+07
     Switzerland        7.474490e+07
     United Kingdom     4.904481e+08
     United States      1.059333e+09

[834 rows x 1 columns]

In [10]:
temd = pd.read_csv('don.csv', delimiter=',')
temd = temd.pivot(index='year', columns='donor', values='donated_amount')
temd = temd.fillna(0)
# temd.to_csv(r'tem-don.csv')
temd

donor,Australia,Austria,Belgium,Brazil,Canada,Chile,Colombia,Cyprus,Czech Republic,Denmark,...,Slovak Republic,Slovenia,Spain,Sweden,Switzerland,Taiwan,Thailand,United Arab Emirates,United Kingdom,United States
year,,,,,,,,,,,,,,,,,,,,,
1973,46285863.0,0.0,39251336.0,0.0,437928427.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,168369255.0,14060941.0,0.0,0.0,0.0,4.425792e+08,1.553264e+09
1974,26950877.0,24126329.0,43588598.0,0.0,68502158.0,0.0,0.0,0.0,0.0,56839286.0,...,0.0,0.0,0.0,30299330.0,64549529.0,0.0,0.0,0.0,1.405379e+09,8.710922e+08
1975,77691781.0,0.0,38863307.0,0.0,93027681.0,0.0,0.0,0.0,0.0,10392556.0,...,0.0,0.0,0.0,201059589.0,103204755.0,0.0,0.0,0.0,2.221879e+08,9.442725e+08
1976,27718070.0,12981849.0,36126619.0,0.0,116287322.0,0.0,0.0,0.0,0.0,28849377.0,...,0.0,0.0,0.0,151806434.0,43577287.0,0.0,0.0,64911546.0,5.161357e+07,8.972902e+08
1977,72648152.0,2608725.0,35853879.0,0.0,38957778.0,0.0,0.0,0.0,0.0,112241594.0,...,0.0,0.0,0.0,143468255.0,111194695.0,0.0,0.0,0.0,8.600113e+08,2.461984e+08
1978,47483698.0,27058314.0,32189217.0,0.0,100516271.0,0.0,0.0,0.0,0.0,2086036.0,...,0.0,0.0,0.0,472112462.0,35883359.0,0.0,0.0,0.0,9.717094e+08,4.384529e+08
1979,9763598.0,2480539.0,30801519.0,0.0,80241209.0,0.0,0.0,0.0,0.0,35943903.0,...,0.0,0.0,0.0,253701905.0,67821487.0,0.0,0.0,0.0,5.012313e+06,7.177796e+08
1980,23283790.0,2720513.0,0.0,0.0,139264006.0,0.0,0.0,0.0,0.0,96585940.0,...,0.0,0.0,0.0,10679246.0,10028652.0,0.0,0.0,0.0,5.673115e+08,6.864224e+09
1981,18425831.0,53422527.0,61917902.0,0.0,546970726.0,0.0,0.0,0.0,0.0,215721283.0,...,0.0,0.0,0.0,151539023.0,18045799.0,0.0,0.0,0.0,7.198102e+06,8.124424e+09
1982,10458375.0,272169.0,0.0,0.0,87937147.0,0.0,0.0,0.0,0.0,122090821.0,...,0.0,0.0,0.0,147903816.0,63684924.0,0.0,0.0,0.0,7.753347e+08,3.462491e+09
1983,7388539.0,17235616.0,46243316.0,0.0,148016945.0,0.0,0.0,0.0,0.0,84368125.0,...,0.0,0.0,0.0,136226862.0,190427090.0,0.0,0.0,0.0,5.716799e+08,1.091122e+09
1984,3698286.0,0.0,0.0,0.0,691336664.0,0.0,0.0,0.0,0.0,131061636.0,...,0.0,0.0,0.0,133481767.0,116248354.0,0.0,0.0,0.0,7.535387e+08,2.515278e+09
1985,6929573.0,87348212.0,4191839.0,0.0,146523445.0,0.0,0.0,0.0,0.0,154044569.0,...,0.0,0.0,0.0,123903610.0,52165585.0,0.0,0.0,0.0,1.255318e+06,2.735617e+09
1986,25229662.0,15801537.0,0.0,0.0,392105553.0,0.0,0.0,0.0,0.0,110720962.0,...,0.0,0.0,0.0,198445181.0,35598036.0,0.0,0.0,0.0,2.273950e+08,1.334668e+09
1987,18309923.0,77374.0,0.0,0.0,331152346.0,0.0,0.0,0.0,0.0,149837777.0,...,0.0,0.0,0.0,72374249.0,87982342.0,0.0,0.0,0.0,8.298941e+08,1.846214e+09
1988,1758350.0,400964.0,0.0,0.0,149433255.0,0.0,0.0,0.0,0.0,119577810.0,...,0.0,0.0,0.0,185535976.0,32738889.0,0.0,0.0,0.0,8.025158e+07,1.051167e+09
1989,163270223.0,18299145.0,183930257.0,0.0,95861356.0,0.0,0.0,0.0,0.0,133430275.0,...,0.0,0.0,100535177.0,946284591.0,75386666.0,0.0,0.0,0.0,2.692294e+08,1.065108e+09
1990,93432068.0,3458667.0,187058124.0,0.0,146349000.0,0.0,0.0,0.0,0.0,58616306.0,...,0.0,0.0,33912950.0,400387605.0,123834846.0,0.0,0.0,0.0,2.704030e+08,1.722306e+09
1991,518306838.0,43662774.0,0.0,0.0,79132048.0,0.0,0.0,0.0,0.0,80582842.0,...,0.0,0.0,134873730.0,173278658.0,157754122.0,0.0,0.0,0.0,2.705959e+08,2.887004e+09
1992,57379649.0,7690278.0,470688315.0,0.0,203523019.0,0.0,0.0,0.0,0.0,40778102.0,...,0.0,0.0,0.0,272478628.0,31332667.0,0.0,0.0,0.0,1.055458e+09,1.139928e+10
1993,37557879.0,8599286.0,75567601.0,0.0,129123101.0,0.0,0.0,0.0,0.0,67062860.0,...,0.0,0.0,36693281.0,117438835.0,43709522.0,0.0,0.0,0.0,4.079418e+08,4.501839e+09
1994,62005978.0,496076.0,26867841.0,0.0,83435990.0,0.0,0.0,0.0,0.0,110637370.0,...,0.0,0.0,6797785.0,171450490.0,40395940.0,45628882.0,0.0,0.0,2.970036e+08,8.154319e+09
1995,87263724.0,2349112.0,45999593.0,0.0,140853583.0,0.0,0.0,0.0,0.0,73451287.0,...,0.0,0.0,24737384.0,233739645.0,37875588.0,0.0,0.0,0.0,3.851630e+08,3.392574e+09
1996,80468022.0,31485810.0,25987887.0,0.0,240599471.0,0.0,0.0,0.0,4724939.0,244013860.0,...,0.0,0.0,41887270.0,142391886.0,63515858.0,0.0,0.0,0.0,9.345205e+08,4.595800e+09
1997,99085271.0,18810672.0,35402467.0,0.0,114731583.0,0.0,0.0,0.0,1151600.0,79381953.0,...,0.0,0.0,61562728.0,126686840.0,101719058.0,0.0,0.0,0.0,7.343658e+08,3.423307e+09
1998,60046657.0,17433736.0,25116690.0,0.0,385748294.0,0.0,0.0,0.0,0.0,15650457.0,...,0.0,0.0,56295291.0,117646650.0,70204297.0,0.0,0.0,0.0,7.037120e+08,2.460766e+09
1999,87775767.0,27735866.0,30505209.0,0.0,434102951.0,0.0,0.0,0.0,0.0,75309242.0,...,0.0,0.0,79380361.0,121378837.0,104482040.0,30163151.0,0.0,0.0,8.472731e+08,7.962084e+09
2000,115957719.0,41623882.0,32342289.0,0.0,356912625.0,0.0,0.0,0.0,0.0,37463179.0,...,0.0,0.0,59684269.0,68464897.0,129146680.0,0.0,0.0,0.0,7.252596e+08,6.008166e+09
2001,99427776.0,64630850.0,31859079.0,0.0,349119993.0,0.0,0.0,0.0,530941.0,77063923.0,...,0.0,0.0,71240556.0,95729319.0,93682742.0,0.0,0.0,0.0,6.876514e+08,4.136147e+09
2002,45235182.0,64136019.0,63495593.0,0.0,242075816.0,117867.0,0.0,0.0,156771.0,91324907.0,...,0.0,0.0,76217540.0,48750953.0,127936461.0,0.0,0.0,0.0,6.501140e+08,4.549559e+09
2003,94571888.0,57940744.0,58875247.0,0.0,154336187.0,32051.0,0.0,0.0,247942.0,57028037.0,...,0.0,0.0,134313618.0,109071656.0,65840038.0,0.0,0.0,0.0,8.382435e+08,1.258474e+09
2004,17256770.0,46228250.0,52561101.0,0.0,172189837.0,37923.0,0.0,0.0,0.0,25482007.0,...,0.0,0.0,62843645.0,58723484.0,61749696.0,0.0,0.0,0.0,8.795959e+08,1.328168e+09
2005,28927690.0,17870615.0,48285276.0,0.0,66617166.0,49967.0,0.0,5599.0,119901.0,125145775.0,...,326093.0,0.0,81547019.0,89823816.0,70896849.0,0.0,0.0,0.0,8.223437e+08,1.350567e+09
2006,27058214.0,8003253.0,58458568.0,0.0,60308595.0,129055.0,0.0,0.0,918070.0,10170167.0,...,0.0,0.0,102707597.0,48832575.0,43757262.0,6324571.0,0.0,0.0,8.009149e+08,1.935937e+09
2007,13864351.0,11550522.0,33187081.0,50889.0,62686742.0,56833.0,77466.0,0.0,0.0,21329239.0,...,0.0,0.0,118856065.0,45890520.0,51309531.0,375139.0,4469.0,0.0,1.019401e+09,1.111447e+09
2008,18754564.0,6949094.0,53059381.0,168870.0,75865089.0,10280.0,6798.0,0.0,230219.0,16290834.0,...,0.0,0.0,152422527.0,40720968.0,39324550.0,348667.0,0.0,0.0,7.881643e+08,1.715190e+09
2009,17680084.0,7871776.0,42809116.0,0.0,74116591.0,40764.0,0.0,0.0,397563.0,6819444.0,...,14202.0,0.0,238613474.0,76554392.0,53471939.0,327156.0,0.0,0.0,9.796740e+08,1.695865e+09
2010,32806019.0,8224524.0,41446751.0,914681.0,66543586.0,89609.0,106531.0,0.0,0.0,21438651.0,...,14132.0,135720.0,128037041.0,94790240.0,53676771.0,287807.0,20992.0,1109303.0,4.359828e+08,1.517053e+09
2011,41545539.0,5945013.0,47828984.0,0.0,49798170.0,0.0,0.0,0.0,164099.0,33654018.0,...,0.0,0.0,100140152.0,57386226.0,39344798.0,282125.0,0.0,590706.0,2.382309e+08,1.158992e+09
2012,55649016.0,9369281.0,35767940.0,0.0,59322273.0,0.0,0.0,0.0,165238.0,14988225.0,...,0.0,0.0,55560499.0,42966784.0,41783411.0,0.0,0.0,1025431.0,3.864977e+08,1.093497e+09
2013,67265056.0,7169039.0,68317348.0,0.0,54784201.0,0.0,0.0,0.0,123152.0,4941770.0,...,41147.0,14308.0,55835945.0,82270421.0,74744897.0,0.0,0.0,0.0,4.904481e+08,1.059333e+09

In [11]:
recipient = recipient.rename(index=str, columns={"commitment_amount_usd_constant": "received_amount"}).drop_duplicates()
recipient

                   received_amount
year recipient
1973 Brazil           3.120750e+08
     Chile            8.805608e+07
     Colombia         5.499448e+08
     Cyprus           9.613414e+06
     India            2.285257e+09
     Korea            1.363707e+09
     Kuwait           3.254830e+05
     Saudi Arabia     6.509700e+04
     Thailand         2.063634e+08
1974 Brazil           3.066010e+08
     Chile            2.576892e+08
     Colombia         2.035458e+08
     Cyprus           1.643228e+07
     India            3.697747e+09
     Korea            1.455639e+09
     Taiwan           1.150480e+05
     Thailand         8.676684e+08
1975 Brazil           1.007257e+08
     Chile            3.654084e+08
     Colombia         1.457792e+08
     Cyprus           5.864941e+06
     India            3.000656e+09
     Korea            2.992260e+08
     Thailand         3.336400e+08
1976 Brazil           8.358048e+07
     Chile            1.555513e+08
     Colombia         1.430827e+08
     Cyprus           3.102226e+07
     India            2.233586e+09
     Korea            9.389526e+08
...                            ...
2009 Taiwan           1.420200e+04
     Thailand         1.038513e+09
2010 Brazil           1.059211e+09
     Chile            1.200879e+08
     Colombia         1.128442e+09
     Hungary          1.413200e+04
     India            3.826640e+09
     Japan            1.246730e+05
     Saudi Arabia     3.525480e+05
     South Africa     9.712085e+08
     Thailand         5.609539e+08
2011 Brazil           1.013211e+09
     Chile            6.381417e+07
     Colombia         7.491562e+08
     India            3.652446e+09
     Saudi Arabia     2.821250e+05
     South Africa     9.433905e+08
     Thailand         1.968424e+08
2012 Brazil           2.443208e+09
     Chile            7.280172e+07
     Colombia         1.009768e+09
     India            4.970366e+09
     South Africa     9.557347e+08
     Thailand         3.336224e+08
2013 Brazil           7.030483e+08
     Chile            3.022933e+08
     Colombia         1.039328e+09
     India            4.550646e+09
     South Africa     1.350212e+09
     Thailand         2.599160e+08

[658 rows x 1 columns]

In [12]:
tem = pd.read_csv('rec.csv', delimiter=',')
tem = tem.pivot(index='year', columns='recipient', values='received_amount')
tem = tem.fillna(0)
# tem.to_csv(r'tem-rec.csv')
tem

recipient,Australia,Austria,Belgium,Brazil,Canada,Chile,Colombia,Cyprus,Czech Republic,Denmark,...,Slovenia,South Africa,Spain,Sweden,Switzerland,Taiwan,Thailand,United Arab Emirates,United Kingdom,United States
year,,,,,,,,,,,,,,,,,,,,,
1973,0.0,0.0,0.0,3.120750e+08,0.000000e+00,88056078.0,5.499448e+08,9613414.0,0.0,0.0,...,0.0,0.000000e+00,0.0,0.0,0.0,0.0,2.063634e+08,0.0,0.0,0.0
1974,0.0,0.0,0.0,3.066010e+08,0.000000e+00,257689227.0,2.035458e+08,16432279.0,0.0,0.0,...,0.0,0.000000e+00,0.0,0.0,0.0,115048.0,8.676684e+08,0.0,0.0,0.0
1975,0.0,0.0,0.0,1.007257e+08,0.000000e+00,365408442.0,1.457792e+08,5864941.0,0.0,0.0,...,0.0,0.000000e+00,0.0,0.0,0.0,0.0,3.336400e+08,0.0,0.0,0.0
1976,0.0,0.0,0.0,8.358048e+07,0.000000e+00,155551297.0,1.430827e+08,31022257.0,0.0,0.0,...,0.0,0.000000e+00,0.0,0.0,0.0,0.0,1.100421e+08,0.0,0.0,0.0
1977,0.0,0.0,0.0,5.014389e+08,0.000000e+00,2568149.0,6.779990e+07,20945184.0,0.0,0.0,...,0.0,0.000000e+00,0.0,0.0,0.0,163198.0,7.158840e+08,3599299.0,0.0,0.0
1978,0.0,0.0,0.0,1.515314e+08,0.000000e+00,4418418.0,5.443868e+07,46647.0,0.0,0.0,...,0.0,0.000000e+00,0.0,0.0,0.0,0.0,8.592789e+08,0.0,0.0,0.0
1979,0.0,0.0,0.0,1.674621e+08,0.000000e+00,49451759.0,1.538800e+07,15837039.0,0.0,0.0,...,0.0,0.000000e+00,0.0,0.0,0.0,0.0,1.283440e+09,0.0,0.0,0.0
1980,54502260.0,157632201.0,147868500.0,3.975914e+08,5.316749e+08,17218386.0,2.573683e+08,87110643.0,0.0,104288895.0,...,0.0,0.000000e+00,285026867.0,35282669.0,0.0,374058844.0,9.028523e+08,174742.0,399202551.0,0.0
1981,747648005.0,163916.0,36477733.0,1.019510e+09,2.540406e+09,24802202.0,1.761001e+08,110234644.0,0.0,0.0,...,0.0,0.000000e+00,199457361.0,24474486.0,0.0,312886996.0,1.178205e+09,1813286.0,558141413.0,0.0
1982,2599450.0,58590672.0,0.0,5.776950e+08,1.701748e+08,25718071.0,1.228920e+09,31348629.0,0.0,0.0,...,0.0,0.000000e+00,77227580.0,0.0,0.0,617069786.0,1.595007e+09,936588.0,0.0,0.0
1983,0.0,0.0,0.0,1.294299e+08,0.000000e+00,33869655.0,1.107145e+08,51405078.0,0.0,0.0,...,0.0,0.000000e+00,0.0,0.0,0.0,54105626.0,1.165433e+09,598545.0,0.0,0.0
1984,0.0,0.0,0.0,6.435931e+08,1.530229e+08,314012953.0,2.044951e+08,79282641.0,0.0,62021691.0,...,0.0,0.000000e+00,0.0,0.0,0.0,247894043.0,1.135099e+09,505928.0,0.0,0.0
1985,0.0,0.0,0.0,1.150189e+09,0.000000e+00,624811340.0,8.350915e+08,39214175.0,0.0,0.0,...,0.0,0.000000e+00,0.0,0.0,0.0,28782961.0,1.151124e+09,136260119.0,0.0,0.0
1986,0.0,0.0,0.0,3.982390e+08,0.000000e+00,123522992.0,3.102120e+08,56716357.0,0.0,0.0,...,0.0,0.000000e+00,0.0,0.0,0.0,21795291.0,7.621215e+08,0.0,0.0,0.0
1987,0.0,0.0,0.0,6.886420e+08,0.000000e+00,62625327.0,7.405900e+07,29088415.0,0.0,0.0,...,0.0,1.058255e+08,0.0,0.0,0.0,14965414.0,1.016034e+09,131760270.0,0.0,0.0
1988,0.0,0.0,0.0,3.195083e+08,0.000000e+00,73331550.0,2.340201e+08,60836704.0,0.0,0.0,...,0.0,1.108490e+05,0.0,0.0,0.0,29459009.0,1.297613e+09,0.0,0.0,0.0
1989,0.0,0.0,0.0,4.707958e+08,1.961661e+06,152229260.0,2.003185e+08,32612810.0,0.0,0.0,...,0.0,3.203999e+08,0.0,0.0,0.0,75026666.0,6.260327e+08,0.0,0.0,0.0
1990,0.0,0.0,0.0,5.464102e+08,0.000000e+00,260281186.0,5.393093e+08,11768247.0,549039.0,0.0,...,0.0,2.718289e+08,0.0,0.0,0.0,0.0,1.790643e+09,0.0,0.0,0.0
1991,0.0,0.0,0.0,1.398521e+09,0.000000e+00,575859750.0,4.849866e+08,24108788.0,392264026.0,0.0,...,0.0,6.465092e+07,0.0,0.0,0.0,5446049.0,1.898190e+09,0.0,0.0,0.0
1992,193553716.0,0.0,0.0,2.697719e+08,0.000000e+00,686092378.0,4.921859e+08,29261936.0,212986243.0,0.0,...,10624910.0,2.344905e+08,0.0,0.0,0.0,0.0,1.014336e+09,0.0,0.0,0.0
1993,79262311.0,132570772.0,0.0,7.266724e+08,8.392544e+07,246885634.0,6.485424e+08,42046495.0,170159661.0,0.0,...,2609520.0,5.419556e+08,0.0,0.0,0.0,0.0,3.338548e+09,0.0,0.0,0.0
1994,321233163.0,0.0,0.0,2.807703e+09,0.000000e+00,98616016.0,3.030169e+08,46104382.0,487593167.0,0.0,...,12375582.0,5.162308e+08,0.0,0.0,0.0,2655902.0,1.416098e+09,9485289.0,0.0,0.0
1995,343759453.0,0.0,0.0,2.573831e+09,0.000000e+00,326285394.0,5.868666e+08,1233692.0,182015721.0,0.0,...,7405043.0,6.262576e+08,0.0,0.0,0.0,2561779.0,7.926555e+08,1579978.0,0.0,0.0
1996,0.0,56293.0,0.0,1.902899e+09,0.000000e+00,66195930.0,1.052282e+09,17809922.0,35124917.0,0.0,...,90121406.0,9.740788e+08,0.0,0.0,0.0,9333721.0,1.671335e+09,1038083.0,0.0,0.0
1997,0.0,0.0,0.0,2.033093e+09,0.000000e+00,180051006.0,9.422617e+07,9602634.0,99553819.0,0.0,...,7858148.0,6.942908e+08,0.0,0.0,0.0,2454079.0,6.371021e+09,1002901.0,0.0,0.0
1998,133176980.0,0.0,0.0,1.758374e+09,0.000000e+00,279286896.0,4.077632e+08,563689.0,120505911.0,0.0,...,8484412.0,6.667894e+08,0.0,0.0,0.0,876129.0,2.437534e+09,461121.0,0.0,0.0
1999,0.0,0.0,0.0,1.319317e+09,0.000000e+00,312658747.0,8.819281e+08,19380977.0,82522618.0,0.0,...,12831539.0,6.699436e+08,0.0,0.0,0.0,603873086.0,3.761640e+09,595520.0,0.0,0.0
2000,0.0,0.0,0.0,1.106359e+09,0.000000e+00,143596162.0,1.899135e+09,5189473.0,145892164.0,0.0,...,32556545.0,7.372216e+08,0.0,0.0,184816.0,779075653.0,1.792838e+09,628944.0,0.0,0.0
2001,0.0,171695803.0,0.0,1.574636e+09,0.000000e+00,290131143.0,5.850221e+08,26263860.0,65382378.0,0.0,...,13913044.0,9.354445e+08,0.0,0.0,0.0,13689330.0,5.323231e+08,2140111.0,0.0,0.0
2002,696882923.0,249428720.0,0.0,1.545039e+09,5.874320e+08,118858994.0,8.352648e+08,23150596.0,60471458.0,0.0,...,7663650.0,6.449907e+08,0.0,0.0,24996.0,170259619.0,1.205362e+09,1783343.0,0.0,4920.0
2003,0.0,0.0,0.0,7.793927e+08,0.000000e+00,74584206.0,1.086178e+09,9421124.0,45608312.0,0.0,...,6291746.0,6.085814e+08,0.0,0.0,19468.0,15103689.0,2.897968e+08,2325618.0,0.0,0.0
2004,0.0,1508.0,0.0,6.466045e+08,0.000000e+00,86004680.0,9.517731e+08,24632806.0,41237106.0,0.0,...,12414136.0,5.407000e+08,0.0,0.0,0.0,17888290.0,7.222324e+08,3451690.0,0.0,0.0
2005,0.0,127534.0,0.0,7.236980e+08,0.000000e+00,73415885.0,1.056910e+09,0.0,46801.0,0.0,...,0.0,9.273798e+08,0.0,0.0,97503.0,0.0,7.507264e+08,0.0,0.0,0.0
2006,0.0,0.0,0.0,4.732624e+08,0.000000e+00,53907751.0,1.617818e+09,0.0,0.0,0.0,...,74572.0,8.531036e+08,0.0,0.0,0.0,0.0,4.754880e+08,0.0,0.0,0.0
2007,0.0,0.0,0.0,4.245966e+08,0.000000e+00,114940960.0,8.002930e+08,4469.0,0.0,0.0,...,105426.0,1.070653e+09,0.0,0.0,0.0,0.0,2.466211e+08,0.0,0.0,104519053.0
2008,0.0,0.0,0.0,5.758902e+08,5.546800e+04,275383474.0,1.190054e+09,0.0,0.0,0.0,...,105521.0,1.148282e+09,0.0,0.0,0.0,0.0,9.382449e+08,0.0,0.0,1019.0
2009,0.0,0.0,0.0,7.839014e+08,0.000000e+00,136810686.0,1.279009e+09,0.0,0.0,0.0,...,0.0,1.281799e+09,0.0,0.0,0.0,14202.0,1.038513e+09,0.0,0.0,0.0
2010,0.0,0.0,0.0,1.059211e+09,0.000000e+00,120087929.0,1.128442e+09,0.0,0.0,0.0,...,0.0,9.712085e+08,0.0,0.0,0.0,0.0,5.609539e+08,0.0,0.0,0.0
2011,0.0,0.0,0.0,1.013211e+09,0.000000e+00,63814172.0,7.491562e+08,0.0,0.0,0.0,...,0.0,9.433905e+08,0.0,0.0,0.0,0.0,1.968424e+08,0.0,0.0,0.0
2012,0.0,0.0,0.0,2.443208e+09,0.000000e+00,72801720.0,1.009768e+09,0.0,0.0,0.0,...,0.0,9.557347e+08,0.0,0.0,0.0,0.0,3.336224e+08,0.0,0.0,0.0
2013,0.0,0.0,0.0,7.030483e+08,0.000000e+00,302293325.0,1.039328e+09,0.0,0.0,0.0,...,0.0,1.350212e+09,0.0,0.0,0.0,0.0,2.599160e+08,0.0,0.0,0.0

In [13]:
#recipient.pivot(index='year', columns='recipient', values='received_amount')
recipient.columns

Index(['received_amount'], dtype='object')

### Visualization 2

#### Get top 10 purposes

In [14]:
purp = aid[['year','commitment_amount_usd_constant','coalesced_purpose_name']]
purp = purp.drop_duplicates()
purpamt = purp.groupby(['coalesced_purpose_name']).sum()[['commitment_amount_usd_constant']]
purpamt = purpamt.sort_values(by='commitment_amount_usd_constant', ascending=False)
purpamt.reset_index()
purpamt['coalesced_purpose_name'] = purpamt.index
purpamt = purpamt.head(10)
purpamt

,commitment_amount_usd_constant,coalesced_purpose_name
coalesced_purpose_name,,
Air transport,3.969155e+10,Air transport
Rail transport,2.049821e+10,Rail transport
Industrial development,1.924099e+10,Industrial development
RESCHEDULING AND REFINANCING,1.479750e+10,RESCHEDULING AND REFINANCING
Power generation/non-renewable sources,1.473391e+10,Power generation/non-renewable sources
Import support (capital goods),9.941346e+09,Import support (capital goods)
Social/ welfare services,9.166238e+09,Social/ welfare services
Power generation/renewable sources,8.420724e+09,Power generation/renewable sources
Telecommunications,8.414346e+09,Telecommunications
Mineral/Metal prospection and exploration,8.072571e+09,Mineral/Metal prospection and exploration

In [15]:
purposes = purpamt[['coalesced_purpose_name']]
# purposes
purplist = purposes.values.tolist()
purplist

[['Air transport'],
 ['Rail transport'],
 ['Industrial development'],
 ['RESCHEDULING AND REFINANCING'],
 ['Power generation/non-renewable sources'],
 ['Import support (capital goods)'],
 ['Social/ welfare services'],
 ['Power generation/renewable sources'],
 ['Telecommunications'],
 ['Mineral/Metal prospection and exploration']]

In [16]:
purps = purp.groupby(['year','coalesced_purpose_name']).sum()[['commitment_amount_usd_constant']]
# purps.to_csv(r'purp.csv')
purps

                                                         commitment_amount_usd_constant
year coalesced_purpose_name
1973 Advanced tech. & managerial training                                  1.762669e+07
     Advanced technical and managerial training                            7.958320e+05
     Agricultural development                                              2.248132e+08
     Agricultural education/training                                       2.210626e+06
     Agricultural inputs                                                   4.065039e+08
     Agricultural land resources                                           2.141171e+06
     Agricultural research                                                 1.339137e+06
     Agricultural services, purpose                                        6.023040e+07
     Agricultural water resources                                          4.017412e+06
     Agriculture, purpose unspecified or does not fi...                    1.555871e+08
     Basic health infrastructure                                           5.689529e+07
     Debt forgiveness                                                      4.103104e+07
     Education facilities and training                                     3.704400e+07
     Education policy & admin. management                                  1.008103e+08
     Electrical transmission/distribution                                  5.138609e+07
     Family planning                                                       1.109148e+07
     Fishing Development                                                   1.755675e+06
     Food security programmes/food aid                                     4.698684e+08
     Forestry development                                                  1.497040e+05
     Formal sector financial intermediaries                                3.072338e+07
     General budget support                                                3.592756e+08
     Government administration                                             1.603750e+07
     Health policy & admin. management                                     1.088751e+08
     Health policy and administrative management                           6.311440e+05
     Higher education                                                      2.144315e+06
     Import support (capital goods)                                        2.918863e+08
     Import support (commodities)                                          1.000538e+09
     Industrial development                                                2.007764e+08
     Industrial policy & admin. mgmt                                       1.169849e+08
     Material relief assistance and services                               7.154240e+05
...                                                                                 ...
2013 Small and medium-sized enterprises (SME) develo...                    8.435044e+06
     Social/ welfare services                                              7.688384e+07
     Std control including hiv/aids                                        5.886570e+05
     Strengthening civil society                                           1.375120e+08
     Support to international NGOs                                         5.945100e+04
     Support to national NGOs                                              1.570553e+06
     Teacher training                                                      1.794858e+07
     Technological research and development                                1.468792e+06
     Telecommunications                                                    5.520572e+06
     Tourism policy and admin. management                                  9.925400e+04
     Tourism policy and administrative management                          2.822417e+06
     Trade education/training                                              8.430200e+04
     Trade facilitation                                                    1.724840e+07
     Trade policy and administrative management                            1.227480e+05
     Transport and Storage, combination of purposes                        2.511958e+08
     Transport policy and administrative management                        3.657212e+06
     Tuberculosis control                                                  1.291000e+03
     Urban development and management                                      2.963654e+08
     Vocational training                                                   1.321891e+07
     Waste management/disposal                                             9.104440e+05
     Water Research                                                        3.289320e+05
     Water Supply and Sanitation, combination of pur...                    1.727000e+03
     Water Supply and Sanitation, purpose unspecifie...                    1.770250e+07
     Water resources policy and administrative manag...                    5.681210e+06
     Water resources policy/admin. mgmt                                    6.325090e+05
     Water resources protection                                            8.120160e+06
     Water supply and sanitation - large systems                           1.482226e+08
     Water transport                                                       1.313320e+05
     Women in development                                                  2.258785e+06
     Women's equality organisations and institutions                       1.954070e+05

[6081 rows x 1 columns]

In [17]:
toppurp = pd.read_csv('purp.csv', delimiter=',')
toppurp = toppurp.pivot(index='year', columns='coalesced_purpose_name', values='commitment_amount_usd_constant')
toppurp = toppurp.fillna(0)
toppurp = toppurp[['Air transport','Rail transport','Industrial development','RESCHEDULING AND REFINANCING','Power generation/non-renewable sources','Import support (capital goods)','Social/ welfare services','Power generation/renewable sources','Telecommunications','Mineral/Metal prospection and exploration']]
toppurp.to_csv(r'top-purposes.csv')

In [33]:
tenpurposes = pd.read_csv('purposes-10.csv', delimiter=',')
tenpurposes = tenpurposes.sort_values(by=['year','commitment_amount_usd_constant'])
tenpurposes.to_csv(r'top-10-purposes.csv')
tenpurposes

,year,coalesced_purpose_name,commitment_amount_usd_constant
2,1973,Power generation/non-renewable sources,27825666
3,1973,Rail transport,95792628
1,1973,Industrial development,200776443
4,1973,Telecommunications,205122036
0,1973,Import support (capital goods),291886347
8,1974,Mineral/Metal prospection and exploration,5135311
5,1974,Air transport,15256725
9,1974,Power generation/non-renewable sources,39880530
11,1974,Rail transport,42563758
10,1974,Power generation/renewable sources,124861445
7,1974,Industrial development,153995109
12,1974,Telecommunications,180475251
6,1974,Import support (capital goods),227194054
16,1975,Mineral/Metal prospection and exploration,11841107
13,1975,Air transport,15829434
17,1975,Power generation/non-renewable sources,33166434
19,1975,Telecommunications,33166434
18,1975,Rail transport,60080677
15,1975,Industrial development,130703901
14,1975,Import support (capital goods),282632241
22,1976,Mineral/Metal prospection and exploration,46994
25,1976,Social/ welfare services,22193818
24,1976,Rail transport,65859994
26,1976,Telecommunications,101268177
21,1976,Industrial development,144403742
20,1976,Import support (capital goods),154515986
23,1976,Power generation/renewable sources,258500419
27,1977,Air transport,704628
30,1977,Mineral/Metal prospection and exploration,20846552
32,1977,Telecommunications,132007996
...,...,...,...
306,2010,Power generation/non-renewable sources,1612781
310,2010,Telecommunications,2591233
305,2010,Industrial development,78399519
307,2010,Power generation/renewable sources,178425707
309,2010,Social/ welfare services,259715668
308,2010,Rail transport,2769998813
314,2011,Power generation/non-renewable sources,200948
318,2011,Telecommunications,774579
313,2011,Mineral/Metal prospection and exploration,1217712
311,2011,Air transport,4105579
312,2011,Industrial development,15173456
317,2011,Social/ welfare services,122564422
316,2011,Rail transport,436777967
315,2011,Power generation/renewable sources,1036425472
321,2012,Mineral/Metal prospection and exploration,545570
326,2012,Telecommunications,1611860
320,2012,Industrial development,2569208
319,2012,Air transport,4390228
322,2012,Power generation/non-renewable sources,49591524
325,2012,Social/ welfare services,68531194
323,2012,Power generation/renewable sources,375992468
324,2012,Rail transport,1619976788
329,2013,Mineral/Metal prospection and exploration,2839501
328,2013,Industrial development,4937413
334,2013,Telecommunications,5520572
327,2013,Air transport,5627464
333,2013,Social/ welfare services,76883840
330,2013,Power generation/non-renewable sources,250838515
331,2013,Power generation/renewable sources,336238470
332,2013,Rail transport,2251372351

### Mini-Project-2: Visualization 3

In [14]:
tempdata = aid[['year','donor','recipient','commitment_amount_usd_constant']]
# donordata = tempdata.groupby(['year','donor'])['commitment_amount_usd_constant'].sum()
# donordata
tempdata = tempdata.loc[tempdata['donor'] == 'New Zealand']
tempdata = tempdata.sort_values(by='year')


tempdata = tempdata.drop(columns=['donor'])
tempdata = tempdata.groupby(['year','recipient'])['commitment_amount_usd_constant'].sum()
tempdata.to_csv(r'kiwi-donations.csv')
tempdata

year  recipient
1981  India            752775.0
1982  Thailand         572352.0
1983  Thailand         216892.0
1985  Thailand        4831732.0
1995  Chile            273712.0
      India            224051.0
      South Africa     983977.0
      Thailand          69294.0
2002  Brazil           214401.0
      Chile            296078.0
      Colombia         365547.0
      India           1083306.0
      South Africa    1745946.0
      Thailand         260043.0
2003  Brazil           260058.0
      Chile            567339.0
      Colombia         190786.0
      India           1798947.0
      South Africa    2009242.0
      Thailand         603022.0
2004  Brazil           278870.0
      Chile            479085.0
      Colombia         221659.0
      India           1720453.0
      Kuwait           153669.0
      South Africa    2303984.0
      Thailand         185190.0
2005  Brazil           293576.0
      Chile            472997.0
      Colombia         113277.0
                        ...
2008  India           1953889.0
      South Africa    1621520.0
      Thailand         373331.0
2009  Brazil           339120.0
      Chile            433699.0
      India           2579805.0
      South Africa    1270041.0
      Thailand          97634.0
2010  Brazil           284989.0
      Chile           1513698.0
      Colombia         109110.0
      India            408698.0
      South Africa    1198622.0
      Thailand           3829.0
2011  Brazil           212413.0
      Chile            278743.0
      India           1640241.0
      South Africa    1350266.0
      Thailand         142135.0
2012  Brazil            97067.0
      Chile           1464630.0
      Colombia          11260.0
      India             33970.0
      South Africa     115737.0
2013  Brazil           133652.0
      Chile            319376.0
      Colombia         244739.0
      India            962568.0
      South Africa     217244.0
      Thailand          60751.0
Name: commitment_amount_usd_constant, Length: 78, dtype: float64

In [28]:
nzdonations = pd.read_csv('kiwi-donations.csv', delimiter=',')
nzdonations = nzdonations.sort_values(by=['year','amount'])
nzdonations.to_csv(r'new-zealand-donations-time.csv')
nzdonations

    year     recipient     amount
0   1981         India   752775.0
1   1982      Thailand   572352.0
2   1983      Thailand   216892.0
3   1985      Thailand  4831732.0
7   1995      Thailand    69294.0
5   1995         India   224051.0
4   1995         Chile   273712.0
6   1995  South Africa   983977.0
8   2002        Brazil   214401.0
13  2002      Thailand   260043.0
9   2002         Chile   296078.0
10  2002      Colombia   365547.0
11  2002         India  1083306.0
12  2002  South Africa  1745946.0
16  2003      Colombia   190786.0
14  2003        Brazil   260058.0
15  2003         Chile   567339.0
19  2003      Thailand   603022.0
17  2003         India  1798947.0
18  2003  South Africa  2009242.0
24  2004        Kuwait   153669.0
26  2004      Thailand   185190.0
22  2004      Colombia   221659.0
20  2004        Brazil   278870.0
21  2004         Chile   479085.0
23  2004         India  1720453.0
25  2004  South Africa  2303984.0
29  2005      Colombia   113277.0
27  2005        Brazil   293576.0
28  2005         Chile   472997.0
..   ...           ...        ...
45  2008        Brazil   446260.0
49  2008  South Africa  1621520.0
48  2008         India  1953889.0
55  2009      Thailand    97634.0
51  2009        Brazil   339120.0
52  2009         Chile   433699.0
54  2009  South Africa  1270041.0
53  2009         India  2579805.0
61  2010      Thailand     3829.0
58  2010      Colombia   109110.0
56  2010        Brazil   284989.0
59  2010         India   408698.0
60  2010  South Africa  1198622.0
57  2010         Chile  1513698.0
66  2011      Thailand   142135.0
62  2011        Brazil   212413.0
63  2011         Chile   278743.0
65  2011  South Africa  1350266.0
64  2011         India  1640241.0
69  2012      Colombia    11260.0
70  2012         India    33970.0
67  2012        Brazil    97067.0
71  2012  South Africa   115737.0
68  2012         Chile  1464630.0
77  2013      Thailand    60751.0
72  2013        Brazil   133652.0
76  2013  South Africa   217244.0
74  2013      Colombia   244739.0
73  2013         Chile   319376.0
75  2013         India   962568.0

[78 rows x 3 columns]

In [29]:
res = pd.read_csv('kiwi-donations.csv', delimiter=',')
res = res.pivot(index='year', columns='recipient',values='amount')
res = res.fillna(0)
# res.to_csv(r'kiwi-don.csv')
res

recipient,Brazil,Chile,Colombia,India,Kuwait,South Africa,Thailand
year,,,,,,,
1981,0.0,0.0,0.0,752775.0,0.0,0.0,0.0
1982,0.0,0.0,0.0,0.0,0.0,0.0,572352.0
1983,0.0,0.0,0.0,0.0,0.0,0.0,216892.0
1985,0.0,0.0,0.0,0.0,0.0,0.0,4831732.0
1995,0.0,273712.0,0.0,224051.0,0.0,983977.0,69294.0
2002,214401.0,296078.0,365547.0,1083306.0,0.0,1745946.0,260043.0
2003,260058.0,567339.0,190786.0,1798947.0,0.0,2009242.0,603022.0
2004,278870.0,479085.0,221659.0,1720453.0,153669.0,2303984.0,185190.0
2005,293576.0,472997.0,113277.0,2088192.0,0.0,1606002.0,582630.0
2006,320951.0,296741.0,86804.0,1205428.0,0.0,2332301.0,148395.0
2007,174175.0,998447.0,20263.0,1520973.0,0.0,1401416.0,64354.0
2008,446260.0,433044.0,8472.0,1953889.0,0.0,1621520.0,373331.0
2009,339120.0,433699.0,0.0,2579805.0,0.0,1270041.0,97634.0
2010,284989.0,1513698.0,109110.0,408698.0,0.0,1198622.0,3829.0
2011,212413.0,278743.0,0.0,1640241.0,0.0,1350266.0,142135.0
2012,97067.0,1464630.0,11260.0,33970.0,0.0,115737.0,0.0
2013,133652.0,319376.0,244739.0,962568.0,0.0,217244.0,60751.0

In [10]:
purpose = aid[['recipient','coalesced_purpose_name']]
purpose = purpose.sort_values(by=['recipient'])

purpose = purpose.groupby(purpose.columns.tolist()).size().reset_index().\
    rename(columns={0:'count'})
purpose

,recipient,coalesced_purpose_name,count
0,Australia,Air transport,21
1,Australia,Industrial development,1
2,Australia,Mineral/Metal prospection and exploration,4
3,Australia,Radio/television/print media,1
4,Australia,Rail transport,1
5,Austria,Agricultural policy and administrative management,1
6,Austria,Air transport,6
7,Austria,Legal and judicial development,1
8,Austria,Material relief assistance and services,2
9,Austria,Sectors not specified,2
10,Belgium,Air transport,2
11,Brazil,Action relating to debt,7
12,Brazil,Administrative costs,240
13,Brazil,Administrative costs (non-sector allocable),12
14,Brazil,Advanced tech. & managerial training,34
15,Brazil,Advanced technical and managerial training,81
16,Brazil,Agrarian reform,1
17,Brazil,Agricultural alternative development,3
18,Brazil,Agricultural co-operatives,7
19,Brazil,Agricultural development,373
20,Brazil,Agricultural education/training,191
21,Brazil,Agricultural extension,3
22,Brazil,Agricultural inputs,8
23,Brazil,Agricultural land resources,43
24,Brazil,Agricultural policy & admin. mgmt,6
25,Brazil,Agricultural policy and administrative management,104
26,Brazil,Agricultural research,90
27,Brazil,Agricultural services,1
28,Brazil,"Agricultural services, purpose",146
29,Brazil,Agricultural water resources,23
...,...,...,...
3389,United Arab Emirates,Industrial policy and administrative management,1
3390,United Arab Emirates,Legal and judicial development,5
3391,United Arab Emirates,Material relief assistance and services,1
3392,United Arab Emirates,Medical services,2
3393,United Arab Emirates,Multisector aid,4
3394,United Arab Emirates,Multisector education/training,1
3395,United Arab Emirates,Primary education,1
3396,United Arab Emirates,RADIO/TELEVISION/PRINT MEDIA,1
3397,United Arab Emirates,Radio/television/print media,3
3398,United Arab Emirates,Reintegration and SALW control,1
3399,United Arab Emirates,Research/scientific institutions,8
3400,United Arab Emirates,SITE PRESERVATION,1
3401,United Arab Emirates,Secondary education,1
3402,United Arab Emirates,Sectors not specified,1
3403,United Arab Emirates,Security system management and reform,1
3404,United Arab Emirates,Social/ welfare services,50
3405,United Arab Emirates,Strengthening civil society,2
3406,United Arab Emirates,Support to non-governmental organizations and ...,1
3407,United Arab Emirates,TEACHER TRAINING,1
3408,United Arab Emirates,TRADE POLICY AND ADMIN. MANAGEMENT,1
3409,United Arab Emirates,Trade policy and administrative management,1
3410,United Arab Emirates,Water transport,2
3411,United Kingdom,Air transport,4
3412,United States,Basic health care,3
3413,United States,Basic health infrastructure,2
3414,United States,Economic and development policy/planning,1
3415,United States,Higher education,4
3416,United States,Housing policy and administrative management,5
3417,United States,Reproductive health care,1
3418,United States,Social/ welfare services,3

In [21]:
temp = temp.sort_values(by=['year'])
temp

,year,donor,recipient,commitment_amount_usd_constant,donated_amount,recieved_amount
64218,1973,Australia,Thailand,41290.0,2.446616e+09,4.904132e+10
70979,1973,Germany,Korea,17070063.0,4.721844e+10,2.529432e+10
64801,1973,United States,India,217258191.0,1.161763e+11,1.339805e+11
64916,1973,Sweden,India,69954880.0,6.364046e+09,1.339805e+11
64096,1973,United Kingdom,Thailand,28433794.0,2.369054e+10,4.904132e+10
62235,1973,Japan,Korea,132168200.0,1.141823e+11,2.529432e+10
64367,1973,United States,Korea,4310646.0,1.161763e+11,2.529432e+10
64627,1973,Italy,Colombia,1360520.0,3.835656e+09,2.553054e+10
64789,1973,Switzerland,India,1695110.0,2.844088e+09,1.339805e+11
62192,1973,Canada,India,49901.0,7.466338e+09,1.339805e+11
70382,1973,Germany,Colombia,25602816.0,4.721844e+10,2.553054e+10
62136,1973,United States,Colombia,10572979.0,1.161763e+11,2.553054e+10
62137,1973,Australia,Thailand,5899.0,2.446616e+09,4.904132e+10
64095,1973,Japan,India,36963131.0,1.141823e+11,1.339805e+11
70312,1973,Sweden,India,618876.0,6.364046e+09,1.339805e+11
70311,1973,France,Thailand,66777621.0,1.545646e+10,4.904132e+10
69854,1973,France,India,52419836.0,1.545646e+10,1.339805e+11
70383,1973,Germany,Korea,34135570.0,4.721844e+10,2.529432e+10
70986,1973,Norway,India,31347898.0,4.416814e+09,1.339805e+11
69367,1973,Canada,India,37405981.0,7.466338e+09,1.339805e+11
70988,1973,Germany,Colombia,838242.0,4.721844e+10,2.553054e+10
66098,1973,Australia,India,831694.0,2.446616e+09,1.339805e+11
66957,1973,Australia,Thailand,17696.0,2.446616e+09,4.904132e+10
66906,1973,Italy,India,39090548.0,3.835656e+09,1.339805e+11
66099,1973,Australia,Thailand,831694.0,2.446616e+09,4.904132e+10
66782,1973,United States,Brazil,60486151.0,1.161763e+11,3.660726e+10
66775,1973,Japan,India,19824939.0,1.141823e+11,1.339805e+11
68500,1973,Canada,Colombia,2135774.0,7.466338e+09,2.553054e+10
62548,1973,Australia,Thailand,176956.0,2.446616e+09,4.904132e+10
66394,1973,Australia,Thailand,283130.0,2.446616e+09,4.904132e+10
...,...,...,...,...,...,...
98511,2013,Poland,Brazil,63571.0,4.031840e+05,3.660726e+10
98512,2013,Greece,India,24288.0,3.266718e+07,1.339805e+11
98513,2013,Poland,Brazil,1657.0,4.031840e+05,3.660726e+10
98505,2013,Portugal,Brazil,134904.0,6.890087e+07,3.660726e+10
98516,2013,Portugal,Brazil,17651.0,6.890087e+07,3.660726e+10
98518,2013,Greece,Chile,1671.0,3.266718e+07,7.334129e+09
95450,2013,Australia,Thailand,25998.0,2.446616e+09,4.904132e+10
98493,2013,Portugal,Chile,55141.0,6.890087e+07,7.334129e+09
98528,2013,New Zealand,South Africa,27772.0,5.674988e+07,1.865556e+10
98519,2013,Portugal,Brazil,197649.0,6.890087e+07,3.660726e+10
98520,2013,New Zealand,India,7911.0,5.674988e+07,1.339805e+11
98521,2013,New Zealand,Brazil,81580.0,5.674988e+07,3.660726e+10
98522,2013,New Zealand,Brazil,52072.0,5.674988e+07,3.660726e+10
98523,2013,New Zealand,Chile,73769.0,5.674988e+07,7.334129e+09
98524,2013,New Zealand,South Africa,112232.0,5.674988e+07,1.865556e+10
98525,2013,New Zealand,India,954657.0,5.674988e+07,1.339805e+11
98526,2013,New Zealand,Chile,245607.0,5.674988e+07,7.334129e+09
98527,2013,New Zealand,Colombia,244739.0,5.674988e+07,2.553054e+10
98529,2013,New Zealand,South Africa,77240.0,5.674988e+07,1.865556e+10
98517,2013,Slovak Republic,Chile,2296.0,3.955740e+05,7.334129e+09
98530,2013,New Zealand,Thailand,60751.0,5.674988e+07,4.904132e+10
98531,2013,Czech Republic,Brazil,4001.0,8.930435e+06,3.660726e+10
98532,2013,Czech Republic,Thailand,127.0,8.930435e+06,4.904132e+10
98533,2013,Czech Republic,Chile,3678.0,8.930435e+06,7.334129e+09
98534,2013,Czech Republic,South Africa,2382.0,8.930435e+06,1.865556e+10
98535,2013,Czech Republic,Colombia,51840.0,8.930435e+06,2.553054e+10
98536,2013,Czech Republic,India,35380.0,8.930435e+06,1.339805e+11
98537,2013,Czech Republic,India,11930.0,8.930435e+06,1.339805e+11
98445,2013,Greece,Thailand,7074.0,3.266718e+07,4.904132e+10
98539,2013,Czech Republic,Chile,7145.0,8.930435e+06,7.334129e+09

In [22]:
t = temp.groupby(['donor','recipient']).sum()[['commitment_amount_usd_constant']]
t
#temp.groupby(['year','recipient']).sum()[['commitment_amount_usd_constant']]

                                    commitment_amount_usd_constant
donor         recipient
Australia     Brazil                                  1.084346e+07
              Chile                                   1.151201e+07
              Colombia                                1.056582e+07
              Cyprus                                  1.872882e+07
              Czech Republic                          6.918000e+03
              Hungary                                 9.846550e+05
              India                                   9.820759e+08
              Korea                                   7.599604e+06
              Poland                                  3.046000e+03
              Saudi Arabia                            7.575000e+03
              Slovenia                                9.665900e+04
              South Africa                            2.408930e+08
              Taiwan                                  5.527790e+05
              Thailand                                1.162746e+09
Austria       Brazil                                  5.222651e+07
              Chile                                   6.426788e+06
              Colombia                                2.023145e+07
              Cyprus                                  5.113082e+07
              Czech Republic                          3.636434e+07
              Estonia                                 6.378410e+05
              Hungary                                 6.387124e+07
              India                                   1.624215e+08
              Korea                                   1.115263e+08
              Kuwait                                  1.241900e+05
              Latvia                                  8.997480e+05
              Lithuania                               1.520246e+06
              Poland                                  3.318433e+07
              Romania                                 3.169509e+07
              Saudi Arabia                            2.145296e+06
              Slovak Republic                         4.470089e+07
...                                                            ...
United States France                                  2.375326e+08
              Greece                                  5.193779e+08
              Hungary                                 1.765305e+09
              Iceland                                 1.806004e+07
              India                                   1.652983e+10
              Ireland                                 9.346387e+08
              Italy                                   2.400034e+09
              Japan                                   2.080978e+09
              Korea                                   1.115436e+10
              Kuwait                                  7.727422e+09
              Latvia                                  1.566049e+08
              Liechtenstein                           1.826437e+07
              Lithuania                               1.824535e+08
              Luxembourg                              5.550398e+08
              New Zealand                             2.255883e+08
              Norway                                  3.680020e+08
              Poland                                  2.508547e+09
              Portugal                                1.751295e+08
              Qatar                                   7.231673e+08
              Romania                                 1.686280e+09
              Saudi Arabia                            4.440014e+09
              Slovak Republic                         9.411386e+07
              Slovenia                                6.917157e+06
              South Africa                            6.678780e+09
              Spain                                   5.617118e+08
              Sweden                                  5.975716e+07
              Taiwan                                  2.831032e+09
              Thailand                                6.495637e+09
              United Arab Emirates                    1.544263e+06
              United Kingdom                          9.573440e+08

[497 rows x 1 columns]

In [94]:
coordinates = pd.merge(purpose, coords, left_on='recipient', right_on='country')
coordinates = coordinates[['recipient','coalesced_purpose_name', 'Latitude', 'Longitude', 'count']]

coordinates

,recipient,coalesced_purpose_name,Latitude,Longitude,count
0,Australia,Air transport,-35.266667,149.133333,21
1,Australia,Industrial development,-35.266667,149.133333,1
2,Australia,Mineral/Metal prospection and exploration,-35.266667,149.133333,4
3,Australia,Radio/television/print media,-35.266667,149.133333,1
4,Australia,Rail transport,-35.266667,149.133333,1
5,Austria,Agricultural policy and administrative management,48.200000,16.366667,1
6,Austria,Air transport,48.200000,16.366667,6
7,Austria,Legal and judicial development,48.200000,16.366667,1
8,Austria,Material relief assistance and services,48.200000,16.366667,2
9,Austria,Sectors not specified,48.200000,16.366667,2
10,Belgium,Air transport,50.833333,4.333333,2
11,Brazil,Action relating to debt,-15.783333,-47.916667,7
12,Brazil,Administrative costs,-15.783333,-47.916667,240
13,Brazil,Administrative costs (non-sector allocable),-15.783333,-47.916667,12
14,Brazil,Advanced tech. & managerial training,-15.783333,-47.916667,34
15,Brazil,Advanced technical and managerial training,-15.783333,-47.916667,81
16,Brazil,Agrarian reform,-15.783333,-47.916667,1
17,Brazil,Agricultural alternative development,-15.783333,-47.916667,3
18,Brazil,Agricultural co-operatives,-15.783333,-47.916667,7
19,Brazil,Agricultural development,-15.783333,-47.916667,373
20,Brazil,Agricultural education/training,-15.783333,-47.916667,191
21,Brazil,Agricultural extension,-15.783333,-47.916667,3
22,Brazil,Agricultural inputs,-15.783333,-47.916667,8
23,Brazil,Agricultural land resources,-15.783333,-47.916667,43
24,Brazil,Agricultural policy & admin. mgmt,-15.783333,-47.916667,6
25,Brazil,Agricultural policy and administrative management,-15.783333,-47.916667,104
26,Brazil,Agricultural research,-15.783333,-47.916667,90
27,Brazil,Agricultural services,-15.783333,-47.916667,1
28,Brazil,"Agricultural services, purpose",-15.783333,-47.916667,146
29,Brazil,Agricultural water resources,-15.783333,-47.916667,23
...,...,...,...,...,...
2377,United Arab Emirates,Industrial policy and administrative management,24.466667,54.366667,1
2378,United Arab Emirates,Legal and judicial development,24.466667,54.366667,5
2379,United Arab Emirates,Material relief assistance and services,24.466667,54.366667,1
2380,United Arab Emirates,Medical services,24.466667,54.366667,2
2381,United Arab Emirates,Multisector aid,24.466667,54.366667,4
2382,United Arab Emirates,Multisector education/training,24.466667,54.366667,1
2383,United Arab Emirates,Primary education,24.466667,54.366667,1
2384,United Arab Emirates,RADIO/TELEVISION/PRINT MEDIA,24.466667,54.366667,1
2385,United Arab Emirates,Radio/television/print media,24.466667,54.366667,3
2386,United Arab Emirates,Reintegration and SALW control,24.466667,54.366667,1
2387,United Arab Emirates,Research/scientific institutions,24.466667,54.366667,8
2388,United Arab Emirates,SITE PRESERVATION,24.466667,54.366667,1
2389,United Arab Emirates,Secondary education,24.466667,54.366667,1
2390,United Arab Emirates,Sectors not specified,24.466667,54.366667,1
2391,United Arab Emirates,Security system management and reform,24.466667,54.366667,1
2392,United Arab Emirates,Social/ welfare services,24.466667,54.366667,50
2393,United Arab Emirates,Strengthening civil society,24.466667,54.366667,2
2394,United Arab Emirates,Support to non-governmental organizations and ...,24.466667,54.366667,1
2395,United Arab Emirates,TEACHER TRAINING,24.466667,54.366667,1
2396,United Arab Emirates,TRADE POLICY AND ADMIN. MANAGEMENT,24.466667,54.366667,1
2397,United Arab Emirates,Trade policy and administrative management,24.466667,54.366667,1
2398,United Arab Emirates,Water transport,24.466667,54.366667,2
2399,United Kingdom,Air transport,51.500000,-0.083333,4
2400,United States,Basic health care,38.883333,-77.000000,3
2401,United States,Basic health infrastructure,38.883333,-77.000000,2
2402,United States,Economic and development policy/planning,38.883333,-77.000000,1
2403,United States,Higher education,38.883333,-77.000000,4
2404,United States,Housing policy and administrative management,38.883333,-77.000000,5
2405,United States,Reproductive health care,38.883333,-77.000000,1
2406,United States,Social/ welfare services,38.883333,-77.000000,3

In [22]:
coords = pd.read_csv('cleandata.csv', delimiter=',')
coords

,country,donated,received,Latitude,Longitude,donatedBillions,receivedBillions
0,Australia,2446616312,2572618261,-35.266667,149.133333,2.446616,2.572618
1,Austria,784068952,770267419,48.200000,16.366667,0.784069,0.770267
2,Belgium,2144445270,184346233,50.833333,4.333333,2.144445,0.184346
3,Brazil,1134440,36607258078,-15.783333,-47.916667,0.001134,36.607258
4,Canada,7466338200,4068652966,45.416667,-75.700000,7.466338,4.068653
5,Chile,564349,7334129130,-33.450000,-70.666667,0.000564,7.334129
6,Colombia,190795,25530536307,4.600000,-74.083333,0.000191,25.530536
7,Cyprus,5599,968154947,35.166667,33.366667,0.000006,0.968155
8,Czech Republic,8930435,2141913341,50.083333,14.466667,0.008930,2.141913
9,Denmark,2952416405,166310586,55.666667,12.583333,2.952416,0.166311
10,Estonia,278942,251349503,59.433333,24.716667,0.000279,0.251350
11,Finland,665953415,180695493,60.166667,24.933333,0.665953,0.180695
12,France,15456459635,237540854,48.866667,2.333333,15.456460,0.237541
13,Germany,47218438821,60164,52.516667,13.400000,47.218439,0.000060
14,Greece,32667185,519377906,37.983333,23.733333,0.032667,0.519378
15,Hungary,324552,2925327491,47.500000,19.083333,0.000325,2.925327
16,Iceland,172501,18060045,64.150000,-21.950000,0.000173,0.018060
17,Ireland,295144458,934638729,53.316667,-6.233333,0.295144,0.934639
18,Italy,3835655974,2400826417,41.900000,12.483333,3.835656,2.400826
19,Japan,114182254172,2081102258,35.683333,139.750000,114.182254,2.081102
20,Korea,1299047720,25294323453,NaN,NaN,1.299048,25.294323
21,Kuwait,1369078319,7771540076,29.366667,47.966667,1.369078,7.771540
22,Liechtenstein,4370700,18393083,47.133333,9.516667,0.004371,0.018393
23,Luxembourg,111554022,555039832,49.600000,6.116667,0.111554,0.555040
24,Monaco,941387,0,43.733333,7.416667,0.000941,0.000000
25,Netherlands,8939647189,0,52.350000,4.916667,8.939647,0.000000
26,New Zealand,56749885,225588310,-41.300000,174.783333,0.056750,0.225588
27,Norway,4416814418,368001981,59.916667,10.750000,4.416814,0.368002
28,Poland,403184,24517225188,52.250000,21.000000,0.000403,24.517225
29,Portugal,68900866,175242606,38.716667,-9.133333,0.068901,0.175243
30,Qatar,104519053,733783749,25.283333,51.533333,0.104519,0.733784
31,Saudi Arabia,1698410689,4877749103,24.650000,46.700000,1.698411,4.877749
32,Slovak Republic,395574,821195623,NaN,NaN,0.000396,0.821196
33,Slovenia,150028,225435200,46.050000,14.516667,0.000150,0.225435
34,Spain,2014695904,561711808,40.400000,-3.683333,2.014696,0.561712
35,Sweden,6364045876,59757155,59.333333,18.050000,6.364046,0.059757
36,Switzerland,2844087953,326783,46.916667,7.466667,2.844088,0.000327
37,Taiwan,89017498,3399554410,25.033333,121.516667,0.089017,3.399554
38,Thailand,25461,49041317440,13.750000,100.516667,0.000025,49.041317
39,United Arab Emirates,67636986,300206472,24.466667,54.366667,0.067637,0.300206
40,United Kingdom,23690539376,957343964,51.500000,-0.083333,23.690539,0.957344
41,United States,116176338066,104524992,38.883333,-77.000000,116.176338,0.104525

In [ ]:
coordinates = pd.merge(aid, coords, left_on='recipient', right_on='country')
coordinates = coordinates[['recipient','coalesced_purpose_name', 'Latitude', 'Longitude', 'count']]

In [ ]:
array = ['']

In [95]:
coordinates.pivot(index='recipient', columns='coalesced_purpose_name', values='count')

coalesced_purpose_name,ADMINISTRATIVE COSTS,ADVANCED TECH. & MANAGERIAL TRAINING,AGRICULTURAL DEVELOPMENT,AGRICULTURAL EDUCATION/TRAINING,AGRICULTURAL POLICY & ADMIN. MGMT,AGRICULTURAL RESEARCH,AGRO-INDUSTRIES,AIR TRANSPORT,Action relating to debt,Administrative costs,...,Water resources policy/admin. mgmt,Water resources protection,Water supply & sanit. - large syst.,Water supply & sanit. - large systems,Water supply - large systems,Water supply and sanitation - large systems,Water transport,Wind power,Women in development,Women's equality organisations and institutions
recipient,,,,,,,,,,,,,,,,,,,,,
Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Brazil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,240.0,...,20.0,30.0,17.0,4.0,2.0,74.0,36.0,2.0,35.0,25.0
Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Chile,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,61.0,...,16.0,20.0,3.0,2.0,NaN,8.0,12.0,NaN,41.0,12.0
Colombia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,137.0,...,9.0,17.0,5.0,2.0,NaN,25.0,13.0,NaN,64.0,27.0
Cyprus,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.0,2.0,NaN,NaN,NaN
Czech Republic,1.0,3.0,1.0,1.0,NaN,NaN,2.0,NaN,NaN,1.0,...,NaN,3.0,NaN,NaN,NaN,14.0,NaN,NaN,1.0,NaN
Denmark,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Estonia,1.0,3.0,1.0,1.0,NaN,1.0,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,13.0,2.0,NaN,2.0,NaN
Finland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Germany,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Greece,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hungary,1.0,2.0,2.0,1.0,NaN,NaN,2.0,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,1.0,NaN
Iceland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ireland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Italy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Japan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Korea,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.0,NaN,...,1.0,NaN,5.0,NaN,NaN,7.0,2.0,NaN,NaN,NaN
Kuwait,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Liechtenstein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Luxembourg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New Zealand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Norway,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
Poland,1.0,7.0,2.0,1.0,2.0,NaN,2.0,1.0,NaN,NaN,...,NaN,3.0,NaN,NaN,NaN,29.0,1.0,NaN,3.0,NaN
Portugal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Qatar,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Saudi Arabia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,...,2.0,NaN,NaN,NaN,NaN,8.0,4.0,NaN,NaN,NaN
Slovak Republic,1.0,7.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,1.0,NaN
Slovenia,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,2.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN
Spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
Sweden,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Switzerland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Taiwan,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
Thailand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,364.0,...,16.0,20.0,8.0,NaN,NaN,37.0,15.0,NaN,19.0,6.0
United Arab Emirates,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN
United Kingdom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
coordinates.to_csv(r'coordinates.csv')

#### Create donor and recipient dataframes

In [8]:
donor = aid[['donor','donated_amount']]
donor.drop_duplicates()

                      donor  donated_amount
0              Saudi Arabia    1.698411e+09
7                    Kuwait    1.369078e+09
32                    Qatar    1.045191e+08
49                   Brazil    1.134440e+06
59                 Colombia    1.907950e+05
78                  Estonia    2.789420e+05
81                  Hungary    3.245520e+05
90            United States    1.161763e+11
787                Thailand    2.546100e+04
1264          Liechtenstein    4.370700e+06
1314        Slovak Republic    3.955740e+05
1371                 Monaco    9.413870e+05
1378                  Chile    5.643490e+05
1418                 Taiwan    8.373750e+07
1426   United Arab Emirates    6.763699e+07
1427                Belgium    2.144445e+09
1428                  Japan    1.141823e+11
1431                Austria    7.840690e+08
1432                  Italy    3.835656e+09
1433                Germany    4.721844e+10
1434                 Sweden    6.364046e+09
1435             Luxembourg    1.115540e+08
1438                  Spain    2.014696e+09
1439                Denmark    2.952416e+09
1440                 France    1.545646e+10
1462                 Norway    4.416814e+09
1472               Portugal    6.890087e+07
1477            Switzerland    2.844088e+09
1479         United Kingdom    2.369054e+10
1488                Finland    6.659534e+08
1491                Ireland    2.951445e+08
1493              Australia    2.446616e+09
1520                 Canada    7.466338e+09
1558                  Korea    1.299048e+09
1740                 Greece    3.266718e+07
3641            Netherlands    8.939647e+09
6374            New Zealand    5.674988e+07
71125                Cyprus    5.599000e+03
71158        Czech Republic    8.930435e+06
71187              Slovenia    1.500280e+05
86284               Iceland    1.725010e+05
98446                Poland    4.031840e+05

In [9]:
recipient = aid[['recipient','recieved_amount']]
recipient.drop_duplicates()

                  recipient  recieved_amount
0                     India     1.339805e+11
1                    Brazil     3.660726e+10
3                    Taiwan     3.399554e+09
4                     Korea     2.529432e+10
7                    Cyprus     9.681549e+08
8                 Lithuania     5.141433e+08
12                 Thailand     4.904132e+10
13          Slovak Republic     8.211956e+08
32            United States     1.045250e+08
49             South Africa     1.865556e+10
50                 Colombia     2.553054e+10
58                   France     2.375409e+08
59                    Chile     7.334129e+09
79                   Poland     2.451723e+10
80           Czech Republic     2.141913e+09
81                  Romania     3.329060e+09
88                   Canada     4.068653e+09
90                Australia     2.572618e+09
91                   Sweden     5.975716e+07
97                  Hungary     2.925327e+09
118                 Denmark     1.663106e+08
156                 Finland     1.806955e+08
165                  Greece     5.193779e+08
171                 Austria     7.702674e+08
235                 Ireland     9.346387e+08
239                   Japan     2.081102e+09
240              Luxembourg     5.550398e+08
245            Saudi Arabia     4.877749e+09
251             New Zealand     2.255883e+08
252          United Kingdom     9.573440e+08
258                 Belgium     1.843462e+08
322                  Norway     3.680020e+08
346                   Italy     2.400826e+09
367                Portugal     1.752426e+08
369                   Qatar     7.337837e+08
394                   Spain     5.617118e+08
419                  Kuwait     7.771540e+09
420           Liechtenstein     1.839308e+07
491                  Latvia     4.234950e+08
652                 Estonia     2.513495e+08
1000                Iceland     1.806004e+07
1294            Switzerland     3.267830e+05
1298                Germany     6.016400e+04
1340               Slovenia     2.254352e+08
12507  United Arab Emirates     3.002065e+08

#### Merge two dataframes

In [21]:
res = pd.merge(donor,recipient, left_on='donor', right_on='recipient')
res.drop_duplicates()

NameError: name 'donor' is not defined

#### Dump donor and recipient dataframes to csv

In [141]:
res.to_csv(r'aid.csv')

In [25]:
res.drop(columns='recipient').drop_duplicates()

                        donor  donated_amount  recieved_amount
0                Saudi Arabia    1.698411e+09     4.877749e+09
7098                   Kuwait    1.369078e+09     7.771540e+09
10173                   Qatar    1.045191e+08     7.337837e+08
12026                  Brazil    1.134440e+06     3.660726e+10
487616               Colombia    1.907950e+05     2.553054e+10
756516                Estonia    2.789420e+05     2.513495e+08
759006                Hungary    3.245520e+05     2.925327e+09
768978          United States    1.161763e+11     1.045250e+08
984096               Thailand    2.546100e+04     4.904132e+10
1004080         Liechtenstein    4.370700e+06     1.839308e+07
1004610       Slovak Republic    3.955740e+05     8.211956e+08
1011706                 Chile    5.643490e+05     7.334129e+09
1361706                Taiwan    8.373750e+07     3.399554e+09
1364686  United Arab Emirates    6.763699e+07     3.002065e+08
1382275               Belgium    2.144445e+09     1.843462e+08
1391803                 Japan    1.141823e+11     2.081102e+09
1504591               Austria    7.840690e+08     7.702674e+08
1527919                 Italy    3.835656e+09     2.400826e+09
1594069               Germany    4.721844e+10     6.016400e+04
1617715                Sweden    6.364046e+09     5.975716e+07
1636599            Luxembourg    1.115540e+08     5.550398e+08
1640235                 Spain    2.014696e+09     5.617118e+08
1826131               Denmark    2.952416e+09     1.663106e+08
1829851                France    1.545646e+10     2.375409e+08
1861251                Norway    4.416814e+09     3.680020e+08
1894060              Portugal    6.890087e+07     1.752426e+08
1898964           Switzerland    2.844088e+09     3.267830e+05
1912199        United Kingdom    2.369054e+10     9.573440e+08
1931531               Finland    6.659534e+08     1.806955e+08
1938326               Ireland    2.951445e+08     9.346387e+08
1959494             Australia    2.446616e+09     2.572618e+09
2037502                Canada    7.466338e+09     4.068653e+09
2132527                 Korea    1.299048e+09     2.529432e+10
3287334                Greece    3.266718e+07     5.193779e+08
3291294           New Zealand    5.674988e+07     2.255883e+08
3292278                Cyprus    5.599000e+03     9.681549e+08
3292581        Czech Republic    8.930435e+06     2.141913e+09
3328587              Slovenia    1.500280e+05     2.254352e+08
3331898               Iceland    1.725010e+05     1.806004e+07
3331901                Poland    4.031840e+05     2.451723e+10

In [26]:
result = res.rename(index=str, columns={"donor": "Country"}).drop_duplicates()

In [28]:
result.drop(columns='recipient')

                      Country  donated_amount  recieved_amount
0                Saudi Arabia    1.698411e+09     4.877749e+09
7098                   Kuwait    1.369078e+09     7.771540e+09
10173                   Qatar    1.045191e+08     7.337837e+08
12026                  Brazil    1.134440e+06     3.660726e+10
487616               Colombia    1.907950e+05     2.553054e+10
756516                Estonia    2.789420e+05     2.513495e+08
759006                Hungary    3.245520e+05     2.925327e+09
768978          United States    1.161763e+11     1.045250e+08
984096               Thailand    2.546100e+04     4.904132e+10
1004080         Liechtenstein    4.370700e+06     1.839308e+07
1004610       Slovak Republic    3.955740e+05     8.211956e+08
1011706                 Chile    5.643490e+05     7.334129e+09
1361706                Taiwan    8.373750e+07     3.399554e+09
1364686  United Arab Emirates    6.763699e+07     3.002065e+08
1382275               Belgium    2.144445e+09     1.843462e+08
1391803                 Japan    1.141823e+11     2.081102e+09
1504591               Austria    7.840690e+08     7.702674e+08
1527919                 Italy    3.835656e+09     2.400826e+09
1594069               Germany    4.721844e+10     6.016400e+04
1617715                Sweden    6.364046e+09     5.975716e+07
1636599            Luxembourg    1.115540e+08     5.550398e+08
1640235                 Spain    2.014696e+09     5.617118e+08
1826131               Denmark    2.952416e+09     1.663106e+08
1829851                France    1.545646e+10     2.375409e+08
1861251                Norway    4.416814e+09     3.680020e+08
1894060              Portugal    6.890087e+07     1.752426e+08
1898964           Switzerland    2.844088e+09     3.267830e+05
1912199        United Kingdom    2.369054e+10     9.573440e+08
1931531               Finland    6.659534e+08     1.806955e+08
1938326               Ireland    2.951445e+08     9.346387e+08
1959494             Australia    2.446616e+09     2.572618e+09
2037502                Canada    7.466338e+09     4.068653e+09
2132527                 Korea    1.299048e+09     2.529432e+10
3287334                Greece    3.266718e+07     5.193779e+08
3291294           New Zealand    5.674988e+07     2.255883e+08
3292278                Cyprus    5.599000e+03     9.681549e+08
3292581        Czech Republic    8.930435e+06     2.141913e+09
3328587              Slovenia    1.500280e+05     2.254352e+08
3331898               Iceland    1.725010e+05     1.806004e+07
3331901                Poland    4.031840e+05     2.451723e+10

In [32]:
result.rename(index=str, columns={"donor": "Country"}).drop(columns='recipient')

                      Country  donated_amount  recieved_amount
0                Saudi Arabia    1.698411e+09     4.877749e+09
7098                   Kuwait    1.369078e+09     7.771540e+09
10173                   Qatar    1.045191e+08     7.337837e+08
12026                  Brazil    1.134440e+06     3.660726e+10
487616               Colombia    1.907950e+05     2.553054e+10
756516                Estonia    2.789420e+05     2.513495e+08
759006                Hungary    3.245520e+05     2.925327e+09
768978          United States    1.161763e+11     1.045250e+08
984096               Thailand    2.546100e+04     4.904132e+10
1004080         Liechtenstein    4.370700e+06     1.839308e+07
1004610       Slovak Republic    3.955740e+05     8.211956e+08
1011706                 Chile    5.643490e+05     7.334129e+09
1361706                Taiwan    8.373750e+07     3.399554e+09
1364686  United Arab Emirates    6.763699e+07     3.002065e+08
1382275               Belgium    2.144445e+09     1.843462e+08
1391803                 Japan    1.141823e+11     2.081102e+09
1504591               Austria    7.840690e+08     7.702674e+08
1527919                 Italy    3.835656e+09     2.400826e+09
1594069               Germany    4.721844e+10     6.016400e+04
1617715                Sweden    6.364046e+09     5.975716e+07
1636599            Luxembourg    1.115540e+08     5.550398e+08
1640235                 Spain    2.014696e+09     5.617118e+08
1826131               Denmark    2.952416e+09     1.663106e+08
1829851                France    1.545646e+10     2.375409e+08
1861251                Norway    4.416814e+09     3.680020e+08
1894060              Portugal    6.890087e+07     1.752426e+08
1898964           Switzerland    2.844088e+09     3.267830e+05
1912199        United Kingdom    2.369054e+10     9.573440e+08
1931531               Finland    6.659534e+08     1.806955e+08
1938326               Ireland    2.951445e+08     9.346387e+08
1959494             Australia    2.446616e+09     2.572618e+09
2037502                Canada    7.466338e+09     4.068653e+09
2132527                 Korea    1.299048e+09     2.529432e+10
3287334                Greece    3.266718e+07     5.193779e+08
3291294           New Zealand    5.674988e+07     2.255883e+08
3292278                Cyprus    5.599000e+03     9.681549e+08
3292581        Czech Republic    8.930435e+06     2.141913e+09
3328587              Slovenia    1.500280e+05     2.254352e+08
3331898               Iceland    1.725010e+05     1.806004e+07
3331901                Poland    4.031840e+05     2.451723e+10

### Convert csv to json

In [65]:
# result.to_json(r'res.json',orient='records')
# result = result.drop(columns='recipient').drop_duplicates()

# result contains three columns - country, donated_amount, recieved_amount
result.columns

Index(['Country', 'donated_amount', 'recieved_amount', 'Countryid'], dtype='object')

In [60]:
result['Countryid'] = result.index

In [62]:
result.to_csv(r'aid-donor-recipient.csv')

### Normalize the dataframe

In [1]:
# Create x, where x the 'scores' column's values as floats
x = result[['donated_amount']].values.astype(float)

# Create a minimum and maximum processor object
min_max_scaler = preprocessing.MinMaxScaler()

# Create an object to transform the data to fit minmax processor
x_scaled = min_max_scaler.fit_transform(x)

result['normalized_donated_amount'] = x_scaled

result['donated_amount'].mean()

NameError: name 'result' is not defined

In [79]:
# Create y, where y the 'scores' column's values as floats
y = result[['recieved_amount']].values.astype(float)

# Create a minimum and maximum processor object
min_max_scaler = preprocessing.MinMaxScaler()

# Create an object to transform the data to fit minmax processor
y_scaled = min_max_scaler.fit_transform(y)

result['normalized_recieved_amount'] = y_scaled

result

result.to_csv(r'aid-normalized.csv')

In [85]:
result['normalized_donated_amount']

0          1.461920e-02
7098       1.178444e-02
10173      8.996105e-04
12026      9.716618e-06
487616     1.594094e-06
756516     2.352829e-06
759006     2.745421e-06
768978     1.000000e+00
984096     1.709643e-07
1004080    3.757307e-05
1004610    3.356751e-06
1011706    4.809499e-06
1361706    7.207311e-04
1364686    5.821443e-04
1382275    1.845849e-02
1391803    9.828357e-01
1504591    6.748908e-03
1527919    3.301576e-02
1594069    4.064376e-01
1617715    5.477915e-02
1636599    9.601648e-04
1640235    1.734166e-02
1826131    2.541319e-02
1829851    1.330431e-01
1861251    3.801815e-02
1894060    5.930233e-04
1898964    2.448074e-02
1912199    2.039188e-01
1931531    5.732216e-03
1938326    2.540439e-03
1959494    2.105946e-02
2037502    6.426724e-02
2132527    1.118164e-02
3287334    2.811380e-04
3291294    4.884324e-04
3292278    0.000000e+00
3292581    7.682146e-05
3328587    1.243188e-06
3331898    1.436627e-06
3331901    3.422255e-06
Name: normalized_donated_amount, dtype: float64

#### Dump dataframe to resjson

In [63]:
resjson = result.to_json()

In [64]:
with open('results.json', 'w') as file:
    json.dump(resjson, file)

### Mini-Project 3: Visualization 3

#### Part 1: Donor-Recipient relationship with Heatmaps or Adjacency matrix

In [69]:
tempdata = aid[['donor','recipient','commitment_amount_usd_constant']]
# donor = temp.groupby(['year','donor'])[['commitment_amount_usd_constant']].sum()
# recipient = temp.groupby(['year','recipient']).sum()[['commitment_amount_usd_constant']]

donor = tempdata.rename(index=str, columns={"commitment_amount_usd_constant": "donated_amount"})
donor = donor.groupby(['donor','recipient'])[['donated_amount']].sum()
donor['donated_amount'].max()
donor

                                    donated_amount
donor         recipient
Australia     Brazil                  1.084346e+07
              Chile                   1.151201e+07
              Colombia                1.056582e+07
              Cyprus                  1.872882e+07
              Czech Republic          6.918000e+03
              Hungary                 9.846550e+05
              India                   9.820759e+08
              Korea                   7.599604e+06
              Poland                  3.046000e+03
              Saudi Arabia            7.575000e+03
              Slovenia                9.665900e+04
              South Africa            2.408930e+08
              Taiwan                  5.527790e+05
              Thailand                1.162746e+09
Austria       Brazil                  5.222651e+07
              Chile                   6.426788e+06
              Colombia                2.023145e+07
              Cyprus                  5.113082e+07
              Czech Republic          3.636434e+07
              Estonia                 6.378410e+05
              Hungary                 6.387124e+07
              India                   1.624215e+08
              Korea                   1.115263e+08
              Kuwait                  1.241900e+05
              Latvia                  8.997480e+05
              Lithuania               1.520246e+06
              Poland                  3.318433e+07
              Romania                 3.169509e+07
              Saudi Arabia            2.145296e+06
              Slovak Republic         4.470089e+07
...                                            ...
United States France                  2.375326e+08
              Greece                  5.193779e+08
              Hungary                 1.765305e+09
              Iceland                 1.806004e+07
              India                   1.652983e+10
              Ireland                 9.346387e+08
              Italy                   2.400034e+09
              Japan                   2.080978e+09
              Korea                   1.115436e+10
              Kuwait                  7.727422e+09
              Latvia                  1.566049e+08
              Liechtenstein           1.826437e+07
              Lithuania               1.824535e+08
              Luxembourg              5.550398e+08
              New Zealand             2.255883e+08
              Norway                  3.680020e+08
              Poland                  2.508547e+09
              Portugal                1.751295e+08
              Qatar                   7.231673e+08
              Romania                 1.686280e+09
              Saudi Arabia            4.440014e+09
              Slovak Republic         9.411386e+07
              Slovenia                6.917157e+06
              South Africa            6.678780e+09
              Spain                   5.617118e+08
              Sweden                  5.975716e+07
              Taiwan                  2.831032e+09
              Thailand                6.495637e+09
              United Arab Emirates    1.544263e+06
              United Kingdom          9.573440e+08

[497 rows x 1 columns]

Convert donor dataframe to csv

In [10]:
donor.to_csv(r'donor-recipient.csv')

#### Part 3: Arc Diagram, Chord diagram or Edge bundling

Get top 5 purposes

In [6]:
purp5 = aid[['year','commitment_amount_usd_constant','coalesced_purpose_name']]
purp5 = purp5.drop_duplicates()
purpamt5 = purp5.groupby(['coalesced_purpose_name']).sum()[['commitment_amount_usd_constant']]
purpamt5 = purpamt5.sort_values(by='commitment_amount_usd_constant', ascending=False)
purpamt5.reset_index()
purpamt5['coalesced_purpose_name'] = purpamt5.index
purpamt5 = purpamt5.head(5)
purpamt5

,commitment_amount_usd_constant,coalesced_purpose_name
coalesced_purpose_name,,
Air transport,3.969155e+10,Air transport
Rail transport,2.049821e+10,Rail transport
Industrial development,1.924099e+10,Industrial development
RESCHEDULING AND REFINANCING,1.479750e+10,RESCHEDULING AND REFINANCING
Power generation/non-renewable sources,1.473391e+10,Power generation/non-renewable sources

In [67]:
pur5 = aid[['donor','recipient','coalesced_purpose_name']]

# Select top 5 purposes
qur5 = pur5.loc[pur5['coalesced_purpose_name'].isin(['Rail transport','Air transport','Industrial development','RESCHEDULING AND REFINANCING','Power generation/non-renewable sources','Import support (capital goods)','Social/ welfare services','Power generation/renewable sources','Telecommunications','Mineral/Metal prospection and exploration'])]

# Group by purposes
qur5 = qur5.groupby(['coalesced_purpose_name','donor','recipient']).count()
# qur5.to_csv(r'purpose-relations.csv')
qur5
# pur5 = pur5.groupby(['donor','recipient']).count()[['coalesced_purpose_name']]
# # pur5.to_csv(r'pur5-count.csv')
# pur5

Empty DataFrame
Columns: []
Index: [(Air transport, Australia, Thailand), (Air transport, Belgium, Thailand), (Air transport, Canada, Czech Republic), (Air transport, Canada, India), (Air transport, Canada, Poland), (Air transport, Canada, Romania), (Air transport, Canada, Thailand), (Air transport, France, Chile), (Air transport, France, Colombia), (Air transport, France, Cyprus), (Air transport, France, Estonia), (Air transport, France, India), (Air transport, France, Romania), (Air transport, France, South Africa), (Air transport, France, Thailand), (Air transport, Germany, Colombia), (Air transport, Italy, Colombia), (Air transport, Japan, Brazil), (Air transport, Japan, Colombia), (Air transport, Japan, Thailand), (Air transport, Korea, Chile), (Air transport, Korea, Thailand), (Air transport, Netherlands, India), (Air transport, Netherlands, Slovak Republic), (Air transport, Norway, India), (Air transport, Norway, South Africa), (Air transport, Norway, Thailand), (Air transport, Spain, Brazil), (Air transport, Spain, Chile), (Air transport, Spain, Colombia), (Air transport, Spain, India), (Air transport, Sweden, Estonia), (Air transport, Sweden, Latvia), (Air transport, Sweden, Lithuania), (Air transport, Sweden, Poland), (Air transport, United Kingdom, India), (Air transport, United Kingdom, Poland), (Air transport, United States, Australia), (Air transport, United States, Austria), (Air transport, United States, Belgium), (Air transport, United States, Brazil), (Air transport, United States, Canada), (Air transport, United States, Chile), (Air transport, United States, Colombia), (Air transport, United States, Czech Republic), (Air transport, United States, Denmark), (Air transport, United States, Finland), (Air transport, United States, France), (Air transport, United States, Greece), (Air transport, United States, Hungary), (Air transport, United States, Iceland), (Air transport, United States, India), (Air transport, United States, Ireland), (Air transport, United States, Italy), (Air transport, United States, Japan), (Air transport, United States, Korea), (Air transport, United States, Lithuania), (Air transport, United States, Luxembourg), (Air transport, United States, New Zealand), (Air transport, United States, Norway), (Air transport, United States, Poland), (Air transport, United States, Portugal), (Air transport, United States, Romania), (Air transport, United States, Saudi Arabia), (Air transport, United States, South Africa), (Air transport, United States, Spain), (Air transport, United States, Taiwan), (Air transport, United States, Thailand), (Air transport, United States, United Arab Emirates), (Air transport, United States, United Kingdom), (Import support (capital goods), Australia, India), (Import support (capital goods), Belgium, Colombia), (Import support (capital goods), Belgium, India), (Import support (capital goods), Denmark, India), (Import support (capital goods), Denmark, Thailand), (Import support (capital goods), France, Chile), (Import support (capital goods), France, India), (Import support (capital goods), Germany, India), (Import support (capital goods), Ireland, Brazil), (Import support (capital goods), Ireland, Colombia), (Import support (capital goods), Ireland, India), (Import support (capital goods), Ireland, South Africa), (Import support (capital goods), Japan, Korea), (Import support (capital goods), Japan, Thailand), (Import support (capital goods), Netherlands, India), (Import support (capital goods), Norway, India), (Import support (capital goods), Spain, Colombia), (Import support (capital goods), Sweden, India), (Import support (capital goods), Switzerland, Chile), (Import support (capital goods), Switzerland, Colombia), (Import support (capital goods), Switzerland, India), (Import support (capital goods), Switzerland, Thailand), (Import support (capital goods), United Kingdom, India), (Import support (capital goods), United States, Korea), (Import support (capital goods), United States, Kuwait), (Import support (capital goods), United States, Thailand), (Industrial development, Australia, India), (Industrial development, Australia, South Africa), (Industrial development, Australia, Thailand), (Industrial development, Austria, Brazil), ...]

[909 rows x 0 columns]

In [22]:
pu5 = pd.read_csv('pur5-count.csv')
pu5.rename(columns={"donor":"source","recipient":"target","coalesced_purpose_name":"value"}, inplace=True)
pu5

            source                target  value
0        Australia                Brazil     97
1        Australia                 Chile    109
2        Australia              Colombia     95
3        Australia                Cyprus      6
4        Australia        Czech Republic      1
5        Australia               Hungary      6
6        Australia                 India    991
7        Australia                 Korea     37
8        Australia                Poland      1
9        Australia          Saudi Arabia      1
10       Australia              Slovenia      3
11       Australia          South Africa    393
12       Australia                Taiwan     11
13       Australia              Thailand   1035
14         Austria                Brazil    519
15         Austria                 Chile     66
16         Austria              Colombia    108
17         Austria                Cyprus     10
18         Austria        Czech Republic     80
19         Austria               Estonia     20
20         Austria               Hungary     79
21         Austria                 India    283
22         Austria                 Korea     14
23         Austria                Kuwait      3
24         Austria                Latvia     14
25         Austria             Lithuania     29
26         Austria                Poland     44
27         Austria               Romania    154
28         Austria          Saudi Arabia     15
29         Austria       Slovak Republic     81
..             ...                   ...    ...
467  United States                France      3
468  United States                Greece      9
469  United States               Hungary    132
470  United States               Iceland      1
471  United States                 India   3502
472  United States               Ireland      9
473  United States                 Italy      8
474  United States                 Japan     11
475  United States                 Korea    268
476  United States                Kuwait      8
477  United States                Latvia     46
478  United States         Liechtenstein      1
479  United States             Lithuania     64
480  United States            Luxembourg      3
481  United States           New Zealand      3
482  United States                Norway      7
483  United States                Poland    206
484  United States              Portugal      7
485  United States                 Qatar      7
486  United States               Romania    422
487  United States          Saudi Arabia     95
488  United States       Slovak Republic     74
489  United States              Slovenia     16
490  United States          South Africa   1670
491  United States                 Spain     19
492  United States                Sweden      4
493  United States                Taiwan     87
494  United States              Thailand   1426
495  United States  United Arab Emirates      6
496  United States        United Kingdom      4

[497 rows x 3 columns]

#### List without unique source values

In [24]:
temp_pu5 = list(pu5.apply(lambda row: {"source": row['source'], "target": row['target'], "value": row['value']}, axis=1))
temp_pu5

[{'source': 'Australia', 'target': 'Brazil', 'value': 97},
 {'source': 'Australia', 'target': 'Chile', 'value': 109},
 {'source': 'Australia', 'target': 'Colombia', 'value': 95},
 {'source': 'Australia', 'target': 'Cyprus', 'value': 6},
 {'source': 'Australia', 'target': 'Czech Republic', 'value': 1},
 {'source': 'Australia', 'target': 'Hungary', 'value': 6},
 {'source': 'Australia', 'target': 'India', 'value': 991},
 {'source': 'Australia', 'target': 'Korea', 'value': 37},
 {'source': 'Australia', 'target': 'Poland', 'value': 1},
 {'source': 'Australia', 'target': 'Saudi Arabia', 'value': 1},
 {'source': 'Australia', 'target': 'Slovenia', 'value': 3},
 {'source': 'Australia', 'target': 'South Africa', 'value': 393},
 {'source': 'Australia', 'target': 'Taiwan', 'value': 11},
 {'source': 'Australia', 'target': 'Thailand', 'value': 1035},
 {'source': 'Austria', 'target': 'Brazil', 'value': 519},
 {'source': 'Austria', 'target': 'Chile', 'value': 66},
 {'source': 'Austria', 'target': 'Colombia', 'value': 108},
 {'source': 'Austria', 'target': 'Cyprus', 'value': 10},
 {'source': 'Austria', 'target': 'Czech Republic', 'value': 80},
 {'source': 'Austria', 'target': 'Estonia', 'value': 20},
 {'source': 'Austria', 'target': 'Hungary', 'value': 79},
 {'source': 'Austria', 'target': 'India', 'value': 283},
 {'source': 'Austria', 'target': 'Korea', 'value': 14},
 {'source': 'Austria', 'target': 'Kuwait', 'value': 3},
 {'source': 'Austria', 'target': 'Latvia', 'value': 14},
 {'source': 'Austria', 'target': 'Lithuania', 'value': 29},
 {'source': 'Austria', 'target': 'Poland', 'value': 44},
 {'source': 'Austria', 'target': 'Romania', 'value': 154},
 {'source': 'Austria', 'target': 'Saudi Arabia', 'value': 15},
 {'source': 'Austria', 'target': 'Slovak Republic', 'value': 81},
 {'source': 'Austria', 'target': 'Slovenia', 'value': 65},
 {'source': 'Austria', 'target': 'South Africa', 'value': 253},
 {'source': 'Austria', 'target': 'Taiwan', 'value': 18},
 {'source': 'Austria', 'target': 'Thailand', 'value': 85},
 {'source': 'Austria', 'target': 'United Arab Emirates', 'value': 4},
 {'source': 'Belgium', 'target': 'Brazil', 'value': 894},
 {'source': 'Belgium', 'target': 'Chile', 'value': 545},
 {'source': 'Belgium', 'target': 'Colombia', 'value': 573},
 {'source': 'Belgium', 'target': 'Cyprus', 'value': 1},
 {'source': 'Belgium', 'target': 'Czech Republic', 'value': 10},
 {'source': 'Belgium', 'target': 'Estonia', 'value': 5},
 {'source': 'Belgium', 'target': 'Hungary', 'value': 15},
 {'source': 'Belgium', 'target': 'India', 'value': 1126},
 {'source': 'Belgium', 'target': 'Korea', 'value': 4},
 {'source': 'Belgium', 'target': 'Latvia', 'value': 4},
 {'source': 'Belgium', 'target': 'Lithuania', 'value': 8},
 {'source': 'Belgium', 'target': 'Poland', 'value': 24},
 {'source': 'Belgium', 'target': 'Romania', 'value': 33},
 {'source': 'Belgium', 'target': 'Saudi Arabia', 'value': 1},
 {'source': 'Belgium', 'target': 'Slovak Republic', 'value': 12},
 {'source': 'Belgium', 'target': 'Slovenia', 'value': 10},
 {'source': 'Belgium', 'target': 'South Africa', 'value': 1261},
 {'source': 'Belgium', 'target': 'Taiwan', 'value': 15},
 {'source': 'Belgium', 'target': 'Thailand', 'value': 223},
 {'source': 'Brazil', 'target': 'Chile', 'value': 1},
 {'source': 'Brazil', 'target': 'Colombia', 'value': 22},
 {'source': 'Brazil', 'target': 'France', 'value': 1},
 {'source': 'Brazil', 'target': 'Japan', 'value': 1},
 {'source': 'Brazil', 'target': 'Saudi Arabia', 'value': 1},
 {'source': 'Brazil', 'target': 'South Africa', 'value': 4},
 {'source': 'Canada', 'target': 'Brazil', 'value': 583},
 {'source': 'Canada', 'target': 'Chile', 'value': 375},
 {'source': 'Canada', 'target': 'Colombia', 'value': 852},
 {'source': 'Canada', 'target': 'Cyprus', 'value': 7},
 {'source': 'Canada', 'target': 'Czech Republic', 'value': 47},
 {'source': 'Canada', 'target': 'Estonia', 'value': 11},
 {'source': 'Canada', 'target': 'Hungary', 'value': 41},
 {'source': 'Canada', 'target': 'India', 'value': 1202},
 {'source': 'Canada', 'target': 'Korea', 'value': 18},
 {'source': 'Canada', 'target': 'Kuwait', 'value': 1},
 {'source': 'Canada', 'target': 'Latvia', 'value': 14},
 {'source': 'Canada', 'target': 'Lithuania', 'value': 25},
 {'source': 'Canada', 'target': 'Poland', 'value': 87},
 {'source': 'Canada', 'target': 'Romania', 'value': 67},
 {'source': 'Canada', 'target': 'Saudi Arabia', 'value': 2},
 {'source': 'Canada', 'target': 'Slovak Republic', 'value': 49},
 {'source': 'Canada', 'target': 'Slovenia', 'value': 9},
 {'source': 'Canada', 'target': 'South Africa', 'value': 670},
 {'source': 'Canada', 'target': 'Thailand', 'value': 465},
 {'source': 'Chile', 'target': 'Brazil', 'value': 5},
 {'source': 'Chile', 'target': 'Chile', 'value': 1},
 {'source': 'Chile', 'target': 'Colombia', 'value': 43},
 {'source': 'Chile', 'target': 'United States', 'value': 1},
 {'source': 'Colombia', 'target': 'Chile', 'value': 17},
 {'source': 'Colombia', 'target': 'Colombia', 'value': 1},
 {'source': 'Colombia', 'target': 'Thailand', 'value': 1},
 {'source': 'Colombia', 'target': 'United States', 'value': 1},
 {'source': 'Cyprus', 'target': 'India', 'value': 1},
 {'source': 'Czech Republic', 'target': 'Brazil', 'value': 3},
 {'source': 'Czech Republic', 'target': 'Chile', 'value': 3},
 {'source': 'Czech Republic', 'target': 'Colombia', 'value': 3},
 {'source': 'Czech Republic', 'target': 'Estonia', 'value': 1},
 {'source': 'Czech Republic', 'target': 'India', 'value': 10},
 {'source': 'Czech Republic', 'target': 'Latvia', 'value': 2},
 {'source': 'Czech Republic', 'target': 'Lithuania', 'value': 4},
 {'source': 'Czech Republic', 'target': 'Romania', 'value': 2},
 {'source': 'Czech Republic', 'target': 'Slovak Republic', 'value': 1},
 {'source': 'Czech Republic', 'target': 'South Africa', 'value': 2},
 {'source': 'Czech Republic', 'target': 'Thailand', 'value': 3},
 {'source': 'Denmark', 'target': 'Brazil', 'value': 3},
 {'source': 'Denmark', 'target': 'Chile', 'value': 15},
 {'source': 'Denmark', 'target': 'Colombia', 'value': 7},
 {'source': 'Denmark', 'target': 'India', 'value': 381},
 {'source': 'Denmark', 'target': 'South Africa', 'value': 359},
 {'source': 'Denmark', 'target': 'Thailand', 'value': 160},
 {'source': 'Denmark', 'target': 'United Arab Emirates', 'value': 5},
 {'source': 'Estonia', 'target': 'Czech Republic', 'value': 1},
 {'source': 'Estonia', 'target': 'India', 'value': 1},
 {'source': 'Estonia', 'target': 'Poland', 'value': 1},
 {'source': 'Finland', 'target': 'Brazil', 'value': 139},
 {'source': 'Finland', 'target': 'Chile', 'value': 78},
 {'source': 'Finland', 'target': 'Colombia', 'value': 89},
 {'source': 'Finland', 'target': 'Czech Republic', 'value': 2},
 {'source': 'Finland', 'target': 'Estonia', 'value': 84},
 {'source': 'Finland', 'target': 'Hungary', 'value': 5},
 {'source': 'Finland', 'target': 'India', 'value': 463},
 {'source': 'Finland', 'target': 'Latvia', 'value': 49},
 {'source': 'Finland', 'target': 'Lithuania', 'value': 33},
 {'source': 'Finland', 'target': 'Poland', 'value': 11},
 {'source': 'Finland', 'target': 'Romania', 'value': 1},
 {'source': 'Finland', 'target': 'Saudi Arabia', 'value': 1},
 {'source': 'Finland', 'target': 'Slovak Republic', 'value': 1},
 {'source': 'Finland', 'target': 'South Africa', 'value': 266},
 {'source': 'Finland', 'target': 'Thailand', 'value': 137},
 {'source': 'France', 'target': 'Brazil', 'value': 1157},
 {'source': 'France', 'target': 'Chile', 'value': 670},
 {'source': 'France', 'target': 'Colombia', 'value': 491},
 {'source': 'France', 'target': 'Cyprus', 'value': 116},
 {'source': 'France', 'target': 'Czech Republic', 'value': 327},
 {'source': 'France', 'target': 'Estonia', 'value': 140},
 {'source': 'France', 'target': 'Hungary', 'value': 275},
 {'source': 'France', 'target': 'India', 'value': 920},
 {'source': 'France', 'target': 'Korea', 'value': 227},
 {'source': 'France', 'target': 'Kuwait', 'value': 84},
 {'source': 'France', 'target': 'Latvia', 'value': 137},
 {'source': 'France', 'target': 'Lithuania', 'value': 178},
 {'source': 'France', 'target': 'Poland', 'value': 325},
 {'source': 'France', 'target': 'Qatar', 'value': 89},
 {'source': 'France', 'target': 'Romania', 'value': 359},
 {'source': 'France', 'target': 'Saudi Arabia', 'value': 156},
 {'source': 'France', 'target': 'Slovak Republic', 'value': 263},
 {'source': 'France', 'target': 'Slovenia', 'value': 155},
 {'source': 'France', 'target': 'South Africa', 'value': 814},
 {'source': 'France', 'target': 'Taiwan', 'value': 121},
 {'source': 'France', 'target': 'Thailand', 'value': 751},
 {'source': 'France', 'target': 'United Arab Emirates', 'value': 95},
 {'source': 'Germany', 'target': 'Brazil', 'value': 2540},
 {'source': 'Germany', 'target': 'Chile', 'value': 976},
 {'source': 'Germany', 'target': 'Colombia', 'value': 1249},
 {'source': 'Germany', 'target': 'Cyprus', 'value': 23},
 {'source': 'Germany', 'target': 'Czech Republic', 'value': 138},
 {'source': 'Germany', 'target': 'Estonia', 'value': 67},
 {'source': 'Germany', 'target': 'Hungary', 'value': 119},
 {'source': 'Germany', 'target': 'India', 'value': 3063},
 {'source': 'Germany', 'target': 'Korea', 'value': 83},
 {'source': 'Germany', 'target': 'Kuwait', 'value': 12},
 {'source': 'Germany', 'target': 'Latvia', 'value': 82},
 {'source': 'Germany', 'target': 'Lithuania', 'value': 96},
 {'source': 'Germany', 'target': 'Poland', 'value': 236},
 {'source': 'Germany', 'target': 'Qatar', 'value': 7},
 {'source': 'Germany', 'target': 'Romania', 'value': 204},
 {'source': 'Germany', 'target': 'Saudi Arabia', 'value': 42},
 {'source': 'Germany', 'target': 'Slovak Republic', 'value': 89},
 {'source': 'Germany', 'target': 'Slovenia', 'value': 56},
 {'source': 'Germany', 'target': 'South Africa', 'value': 1939},
 {'source': 'Germany', 'target': 'Taiwan', 'value': 21},
 {'source': 'Germany', 'target': 'Thailand', 'value': 766},
 {'source': 'Germany', 'target': 'United Arab Emirates', 'value': 15},
 {'source': 'Greece', 'target': 'Brazil', 'value': 83},
 {'source': 'Greece', 'target': 'Chile', 'value': 52},
 {'source': 'Greece', 'target': 'Colombia', 'value': 18},
 {'source': 'Greece', 'target': 'Cyprus', 'value': 12},
 {'source': 'Greece', 'target': 'Czech Republic', 'value': 4},
 {'source': 'Greece', 'target': 'Estonia', 'value': 5},
 {'source': 'Greece', 'target': 'Hungary', 'value': 4},
 {'source': 'Greece', 'target': 'India', 'value': 45},
 {'source': 'Greece', 'target': 'Korea', 'value': 3},
 {'source': 'Greece', 'target': 'Latvia', 'value': 4},
 {'source': 'Greece', 'target': 'Lithuania', 'value': 4},
 {'source': 'Greece', 'target': 'Poland', 'value': 12},
 {'source': 'Greece', 'target': 'Romania', 'value': 66},
 {'source': 'Greece', 'target': 'Saudi Arabia', 'value': 11},
 {'source': 'Greece', 'target': 'Slovak Republic', 'value': 4},
 {'source': 'Greece', 'target': 'Slovenia', 'value': 8},
 {'source': 'Greece', 'target': 'South Africa', 'value': 58},
 {'source': 'Greece', 'target': 'Taiwan', 'value': 4},
 {'source': 'Greece', 'target': 'Thailand', 'value': 42},
 {'source': 'Greece', 'target': 'United Arab Emirates', 'value': 1},
 {'source': 'Hungary', 'target': 'Canada', 'value': 1},
 {'source': 'Hungary', 'target': 'Romania', 'value': 8},
 {'source': 'Iceland', 'target': 'India', 'value': 1},
 {'source': 'Iceland', 'target': 'South Africa', 'value': 2},
 {'source': 'Ireland', 'target': 'Brazil', 'value': 314},
 {'source': 'Ireland', 'target': 'Chile', 'value': 69},
 {'source': 'Ireland', 'target': 'Colombia', 'value': 180},
 {'source': 'Ireland', 'target': 'Hungary', 'value': 7},
 {'source': 'Ireland', 'target': 'India', 'value': 610},
 {'source': 'Ireland', 'target': 'Korea', 'value': 2},
 {'source': 'Ireland', 'target': 'Latvia', 'value': 1},
 {'source': 'Ireland', 'target': 'Romania', 'value': 12},
 {'source': 'Ireland', 'target': 'Slovak Republic', 'value': 1},
 {'source': 'Ireland', 'target': 'South Africa', 'value': 1090},
 {'source': 'Ireland', 'target': 'Thailand', 'value': 66},
 {'source': 'Italy', 'target': 'Brazil', 'value': 1834},
 {'source': 'Italy', 'target': 'Chile', 'value': 303},
 {'source': 'Italy', 'target': 'Colombia', 'value': 487},
 {'source': 'Italy', 'target': 'Cyprus', 'value': 19},
 {'source': 'Italy', 'target': 'Czech Republic', 'value': 51},
 {'source': 'Italy', 'target': 'Estonia', 'value': 17},
 {'source': 'Italy', 'target': 'Hungary', 'value': 66},
 {'source': 'Italy', 'target': 'India', 'value': 1210},
 {'source': 'Italy', 'target': 'Korea', 'value': 11},
 {'source': 'Italy', 'target': 'Kuwait', 'value': 2},
 {'source': 'Italy', 'target': 'Latvia', 'value': 11},
 {'source': 'Italy', 'target': 'Lithuania', 'value': 20},
 {'source': 'Italy', 'target': 'Poland', 'value': 77},
 {'source': 'Italy', 'target': 'Romania', 'value': 158},
 {'source': 'Italy', 'target': 'Saudi Arabia', 'value': 7},
 {'source': 'Italy', 'target': 'Slovak Republic', 'value': 39},
 {'source': 'Italy', 'target': 'Slovenia', 'value': 39},
 {'source': 'Italy', 'target': 'South Africa', 'value': 237},
 {'source': 'Italy', 'target': 'Taiwan', 'value': 1},
 {'source': 'Italy', 'target': 'Thailand', 'value': 135},
 {'source': 'Italy', 'target': 'United Arab Emirates', 'value': 1},
 {'source': 'Japan', 'target': 'Brazil', 'value': 1925},
 {'source': 'Japan', 'target': 'Chile', 'value': 875},
 {'source': 'Japan', 'target': 'Colombia', 'value': 998},
 {'source': 'Japan', 'target': 'Cyprus', 'value': 1},
 {'source': 'Japan', 'target': 'Czech Republic', 'value': 39},
 {'source': 'Japan', 'target': 'Estonia', 'value': 28},
 {'source': 'Japan', 'target': 'Hungary', 'value': 53},
 {'source': 'Japan', 'target': 'India', 'value': 1745},
 {'source': 'Japan', 'target': 'Korea', 'value': 141},
 {'source': 'Japan', 'target': 'Kuwait', 'value': 7},
 {'source': 'Japan', 'target': 'Latvia', 'value': 37},
 {'source': 'Japan', 'target': 'Lithuania', 'value': 32},
 {'source': 'Japan', 'target': 'Poland', 'value': 44},
 {'source': 'Japan', 'target': 'Qatar', 'value': 6},
 {'source': 'Japan', 'target': 'Romania', 'value': 112},
 {'source': 'Japan', 'target': 'Saudi Arabia', 'value': 178},
 {'source': 'Japan', 'target': 'Slovak Republic', 'value': 37},
 {'source': 'Japan', 'target': 'Slovenia', 'value': 10},
 {'source': 'Japan', 'target': 'South Africa', 'value': 643},
 {'source': 'Japan', 'target': 'Taiwan', 'value': 7},
 {'source': 'Japan', 'target': 'Thailand', 'value': 2469},
 {'source': 'Japan', 'target': 'United Arab Emirates', 'value': 12},
 {'source': 'Korea', 'target': 'Brazil', 'value': 67},
 {'source': 'Korea', 'target': 'Chile', 'value': 54},
 {'source': 'Korea', 'target': 'Colombia', 'value': 243},
 {'source': 'Korea', 'target': 'India', 'value': 168},
 {'source': 'Korea', 'target': 'Saudi Arabia', 'value': 4},
 {'source': 'Korea', 'target': 'South Africa', 'value': 62},
 {'source': 'Korea', 'target': 'Thailand', 'value': 759},
 {'source': 'Kuwait', 'target': 'Cyprus', 'value': 9},
 {'source': 'Kuwait', 'target': 'India', 'value': 9},
 {'source': 'Kuwait', 'target': 'Lithuania', 'value': 1},
 {'source': 'Kuwait', 'target': 'Slovak Republic', 'value': 1},
 {'source': 'Kuwait', 'target': 'Thailand', 'value': 5},
 {'source': 'Liechtenstein', 'target': 'Austria', 'value': 6},
 {'source': 'Liechtenstein', 'target': 'Colombia', 'value': 4},
 {'source': 'Liechtenstein', 'target': 'Czech Republic', 'value': 10},
 {'source': 'Liechtenstein', 'target': 'Estonia', 'value': 2},
 {'source': 'Liechtenstein', 'target': 'Finland', 'value': 2},
 {'source': 'Liechtenstein', 'target': 'Germany', 'value': 2},
 {'source': 'Liechtenstein', 'target': 'Hungary', 'value': 13},
 {'source': 'Liechtenstein', 'target': 'India', 'value': 4},
 {'source': 'Liechtenstein', 'target': 'Italy', 'value': 6},
 {'source': 'Liechtenstein', 'target': 'Latvia', 'value': 2},
 {'source': 'Liechtenstein', 'target': 'Liechtenstein', 'value': 4},
 {'source': 'Liechtenstein', 'target': 'Lithuania', 'value': 2},
 {'source': 'Liechtenstein', 'target': 'Poland', 'value': 17},
 {'source': 'Liechtenstein', 'target': 'Romania', 'value': 24},
 {'source': 'Liechtenstein', 'target': 'Slovak Republic', 'value': 1},
 {'source': 'Liechtenstein', 'target': 'Slovenia', 'value': 1},
 {'source': 'Liechtenstein', 'target': 'Switzerland', 'value': 5},
 {'source': 'Liechtenstein', 'target': 'Thailand', 'value': 1},
 {'source': 'Luxembourg', 'target': 'Brazil', 'value': 246},
 {'source': 'Luxembourg', 'target': 'Chile', 'value': 94},
 {'source': 'Luxembourg', 'target': 'Colombia', 'value': 170},
 {'source': 'Luxembourg', 'target': 'Czech Republic', 'value': 1},
 {'source': 'Luxembourg', 'target': 'India', 'value': 608},
 {'source': 'Luxembourg', 'target': 'Romania', 'value': 1},
 {'source': 'Luxembourg', 'target': 'Slovak Republic', 'value': 1},
 {'source': 'Luxembourg', 'target': 'South Africa', 'value': 52},
 {'source': 'Luxembourg', 'target': 'Thailand', 'value': 39},
 {'source': 'Monaco', 'target': 'Portugal', 'value': 1},
 {'source': 'Monaco', 'target': 'Slovenia', 'value': 4},
 {'source': 'Monaco', 'target': 'South Africa', 'value': 6},
 {'source': 'Netherlands', 'target': 'Brazil', 'value': 152},
 {'source': 'Netherlands', 'target': 'Chile', 'value': 151},
 {'source': 'Netherlands', 'target': 'Colombia', 'value': 512},
 {'source': 'Netherlands', 'target': 'Cyprus', 'value': 3},
 {'source': 'Netherlands', 'target': 'Czech Republic', 'value': 76},
 {'source': 'Netherlands', 'target': 'Estonia', 'value': 30},
 {'source': 'Netherlands', 'target': 'Hungary', 'value': 84},
 {'source': 'Netherlands', 'target': 'India', 'value': 1033},
 {'source': 'Netherlands', 'target': 'Korea', 'value': 8},
 {'source': 'Netherlands', 'target': 'Kuwait', 'value': 2},
 {'source': 'Netherlands', 'target': 'Latvia', 'value': 58},
 {'source': 'Netherlands', 'target': 'Lithuania', 'value': 40},
 {'source': 'Netherlands', 'target': 'Poland', 'value': 91},
 {'source': 'Netherlands', 'target': 'Romania', 'value': 139},
 {'source': 'Netherlands', 'target': 'Saudi Arabia', 'value': 5},
 {'source': 'Netherlands', 'target': 'Slovak Republic', 'value': 77},
 {'source': 'Netherlands', 'target': 'Slovenia', 'value': 29},
 {'source': 'Netherlands', 'target': 'South Africa', 'value': 948},
 {'source': 'Netherlands', 'target': 'Thailand', 'value': 205},
 {'source': 'New Zealand', 'target': 'Brazil', 'value': 41},
 {'source': 'New Zealand', 'target': 'Chile', 'value': 47},
 {'source': 'New Zealand', 'target': 'Colombia', 'value': 19},
 {'source': 'New Zealand', 'target': 'India', 'value': 67},
 {'source': 'New Zealand', 'target': 'Kuwait', 'value': 1},
 {'source': 'New Zealand', 'target': 'South Africa', 'value': 115},
 {'source': 'New Zealand', 'target': 'Thailand', 'value': 38},
 {'source': 'Norway', 'target': 'Brazil', 'value': 562},
 {'source': 'Norway', 'target': 'Chile', 'value': 157},
 {'source': 'Norway', 'target': 'Colombia', 'value': 507},
 {'source': 'Norway', 'target': 'Cyprus', 'value': 2},
 {'source': 'Norway', 'target': 'Czech Republic', 'value': 6},
 {'source': 'Norway', 'target': 'Estonia', 'value': 28},
 {'source': 'Norway', 'target': 'Hungary', 'value': 10},
 {'source': 'Norway', 'target': 'India', 'value': 1567},
 {'source': 'Norway', 'target': 'Latvia', 'value': 25},
 {'source': 'Norway', 'target': 'Lithuania', 'value': 33},
 {'source': 'Norway', 'target': 'Poland', 'value': 25},
 {'source': 'Norway', 'target': 'Romania', 'value': 39},
 {'source': 'Norway', 'target': 'Saudi Arabia', 'value': 11},
 {'source': 'Norway', 'target': 'Slovak Republic', 'value': 10},
 {'source': 'Norway', 'target': 'Slovenia', 'value': 4},
 {'source': 'Norway', 'target': 'South Africa', 'value': 1388},
 {'source': 'Norway', 'target': 'Thailand', 'value': 313},
 {'source': 'Poland', 'target': 'Brazil', 'value': 3},
 {'source': 'Poland', 'target': 'Colombia', 'value': 2},
 {'source': 'Poland', 'target': 'India', 'value': 7},
 {'source': 'Poland', 'target': 'South Africa', 'value': 7},

#### Get unique source values

In [36]:
unique_pu5 = pd.Index(pu5['source']
                      .append(pu5['target'])
                      .reset_index(drop=True).unique())
unique_pu5

Index(['Australia', 'Austria', 'Belgium', 'Brazil', 'Canada', 'Chile',
       'Colombia', 'Cyprus', 'Czech Republic', 'Denmark', 'Estonia', 'Finland',
       'France', 'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland', 'Italy',
       'Japan', 'Korea', 'Kuwait', 'Liechtenstein', 'Luxembourg', 'Monaco',
       'Netherlands', 'New Zealand', 'Norway', 'Poland', 'Portugal', 'Qatar',
       'Saudi Arabia', 'Slovak Republic', 'Slovenia', 'Spain', 'Sweden',
       'Switzerland', 'Taiwan', 'Thailand', 'United Arab Emirates',
       'United Kingdom', 'United States', 'India', 'South Africa', 'Latvia',
       'Lithuania', 'Romania'],
      dtype='object')

#### Create grouped dictionary

In [40]:
group_dict = {}
counter = 0
for src in unique_pu5:
    counter += 1
    group_dict[src] = counter

group_dict

{'Australia': 1,
 'Austria': 2,
 'Belgium': 3,
 'Brazil': 4,
 'Canada': 5,
 'Chile': 6,
 'Colombia': 7,
 'Cyprus': 8,
 'Czech Republic': 9,
 'Denmark': 10,
 'Estonia': 11,
 'Finland': 12,
 'France': 13,
 'Germany': 14,
 'Greece': 15,
 'Hungary': 16,
 'Iceland': 17,
 'Ireland': 18,
 'Italy': 19,
 'Japan': 20,
 'Korea': 21,
 'Kuwait': 22,
 'Liechtenstein': 23,
 'Luxembourg': 24,
 'Monaco': 25,
 'Netherlands': 26,
 'New Zealand': 27,
 'Norway': 28,
 'Poland': 29,
 'Portugal': 30,
 'Qatar': 31,
 'Saudi Arabia': 32,
 'Slovak Republic': 33,
 'Slovenia': 34,
 'Spain': 35,
 'Sweden': 36,
 'Switzerland': 37,
 'Taiwan': 38,
 'Thailand': 39,
 'United Arab Emirates': 40,
 'United Kingdom': 41,
 'United States': 42,
 'India': 43,
 'South Africa': 44,
 'Latvia': 45,
 'Lithuania': 46,
 'Romania': 47}

#### Create links_list

In [30]:
links_list = []
for link in temp_pu5:
    record = {"source":unique_pu5.get_loc(link['source']),
     "target": unique_pu5.get_loc(link['target']), "value":link['value']}
    links_list.append(record)

links_list

[{'source': 0, 'target': 3, 'value': 97},
 {'source': 0, 'target': 5, 'value': 109},
 {'source': 0, 'target': 6, 'value': 95},
 {'source': 0, 'target': 7, 'value': 6},
 {'source': 0, 'target': 8, 'value': 1},
 {'source': 0, 'target': 15, 'value': 6},
 {'source': 0, 'target': 42, 'value': 991},
 {'source': 0, 'target': 20, 'value': 37},
 {'source': 0, 'target': 28, 'value': 1},
 {'source': 0, 'target': 31, 'value': 1},
 {'source': 0, 'target': 33, 'value': 3},
 {'source': 0, 'target': 43, 'value': 393},
 {'source': 0, 'target': 37, 'value': 11},
 {'source': 0, 'target': 38, 'value': 1035},
 {'source': 1, 'target': 3, 'value': 519},
 {'source': 1, 'target': 5, 'value': 66},
 {'source': 1, 'target': 6, 'value': 108},
 {'source': 1, 'target': 7, 'value': 10},
 {'source': 1, 'target': 8, 'value': 80},
 {'source': 1, 'target': 10, 'value': 20},
 {'source': 1, 'target': 15, 'value': 79},
 {'source': 1, 'target': 42, 'value': 283},
 {'source': 1, 'target': 20, 'value': 14},
 {'source': 1, 'target': 21, 'value': 3},
 {'source': 1, 'target': 44, 'value': 14},
 {'source': 1, 'target': 45, 'value': 29},
 {'source': 1, 'target': 28, 'value': 44},
 {'source': 1, 'target': 46, 'value': 154},
 {'source': 1, 'target': 31, 'value': 15},
 {'source': 1, 'target': 32, 'value': 81},
 {'source': 1, 'target': 33, 'value': 65},
 {'source': 1, 'target': 43, 'value': 253},
 {'source': 1, 'target': 37, 'value': 18},
 {'source': 1, 'target': 38, 'value': 85},
 {'source': 1, 'target': 39, 'value': 4},
 {'source': 2, 'target': 3, 'value': 894},
 {'source': 2, 'target': 5, 'value': 545},
 {'source': 2, 'target': 6, 'value': 573},
 {'source': 2, 'target': 7, 'value': 1},
 {'source': 2, 'target': 8, 'value': 10},
 {'source': 2, 'target': 10, 'value': 5},
 {'source': 2, 'target': 15, 'value': 15},
 {'source': 2, 'target': 42, 'value': 1126},
 {'source': 2, 'target': 20, 'value': 4},
 {'source': 2, 'target': 44, 'value': 4},
 {'source': 2, 'target': 45, 'value': 8},
 {'source': 2, 'target': 28, 'value': 24},
 {'source': 2, 'target': 46, 'value': 33},
 {'source': 2, 'target': 31, 'value': 1},
 {'source': 2, 'target': 32, 'value': 12},
 {'source': 2, 'target': 33, 'value': 10},
 {'source': 2, 'target': 43, 'value': 1261},
 {'source': 2, 'target': 37, 'value': 15},
 {'source': 2, 'target': 38, 'value': 223},
 {'source': 3, 'target': 5, 'value': 1},
 {'source': 3, 'target': 6, 'value': 22},
 {'source': 3, 'target': 12, 'value': 1},
 {'source': 3, 'target': 19, 'value': 1},
 {'source': 3, 'target': 31, 'value': 1},
 {'source': 3, 'target': 43, 'value': 4},
 {'source': 4, 'target': 3, 'value': 583},
 {'source': 4, 'target': 5, 'value': 375},
 {'source': 4, 'target': 6, 'value': 852},
 {'source': 4, 'target': 7, 'value': 7},
 {'source': 4, 'target': 8, 'value': 47},
 {'source': 4, 'target': 10, 'value': 11},
 {'source': 4, 'target': 15, 'value': 41},
 {'source': 4, 'target': 42, 'value': 1202},
 {'source': 4, 'target': 20, 'value': 18},
 {'source': 4, 'target': 21, 'value': 1},
 {'source': 4, 'target': 44, 'value': 14},
 {'source': 4, 'target': 45, 'value': 25},
 {'source': 4, 'target': 28, 'value': 87},
 {'source': 4, 'target': 46, 'value': 67},
 {'source': 4, 'target': 31, 'value': 2},
 {'source': 4, 'target': 32, 'value': 49},
 {'source': 4, 'target': 33, 'value': 9},
 {'source': 4, 'target': 43, 'value': 670},
 {'source': 4, 'target': 38, 'value': 465},
 {'source': 5, 'target': 3, 'value': 5},
 {'source': 5, 'target': 5, 'value': 1},
 {'source': 5, 'target': 6, 'value': 43},
 {'source': 5, 'target': 41, 'value': 1},
 {'source': 6, 'target': 5, 'value': 17},
 {'source': 6, 'target': 6, 'value': 1},
 {'source': 6, 'target': 38, 'value': 1},
 {'source': 6, 'target': 41, 'value': 1},
 {'source': 7, 'target': 42, 'value': 1},
 {'source': 8, 'target': 3, 'value': 3},
 {'source': 8, 'target': 5, 'value': 3},
 {'source': 8, 'target': 6, 'value': 3},
 {'source': 8, 'target': 10, 'value': 1},
 {'source': 8, 'target': 42, 'value': 10},
 {'source': 8, 'target': 44, 'value': 2},
 {'source': 8, 'target': 45, 'value': 4},
 {'source': 8, 'target': 46, 'value': 2},
 {'source': 8, 'target': 32, 'value': 1},
 {'source': 8, 'target': 43, 'value': 2},
 {'source': 8, 'target': 38, 'value': 3},
 {'source': 9, 'target': 3, 'value': 3},
 {'source': 9, 'target': 5, 'value': 15},
 {'source': 9, 'target': 6, 'value': 7},
 {'source': 9, 'target': 42, 'value': 381},
 {'source': 9, 'target': 43, 'value': 359},
 {'source': 9, 'target': 38, 'value': 160},
 {'source': 9, 'target': 39, 'value': 5},
 {'source': 10, 'target': 8, 'value': 1},
 {'source': 10, 'target': 42, 'value': 1},
 {'source': 10, 'target': 28, 'value': 1},
 {'source': 11, 'target': 3, 'value': 139},
 {'source': 11, 'target': 5, 'value': 78},
 {'source': 11, 'target': 6, 'value': 89},
 {'source': 11, 'target': 8, 'value': 2},
 {'source': 11, 'target': 10, 'value': 84},
 {'source': 11, 'target': 15, 'value': 5},
 {'source': 11, 'target': 42, 'value': 463},
 {'source': 11, 'target': 44, 'value': 49},
 {'source': 11, 'target': 45, 'value': 33},
 {'source': 11, 'target': 28, 'value': 11},
 {'source': 11, 'target': 46, 'value': 1},
 {'source': 11, 'target': 31, 'value': 1},
 {'source': 11, 'target': 32, 'value': 1},
 {'source': 11, 'target': 43, 'value': 266},
 {'source': 11, 'target': 38, 'value': 137},
 {'source': 12, 'target': 3, 'value': 1157},
 {'source': 12, 'target': 5, 'value': 670},
 {'source': 12, 'target': 6, 'value': 491},
 {'source': 12, 'target': 7, 'value': 116},
 {'source': 12, 'target': 8, 'value': 327},
 {'source': 12, 'target': 10, 'value': 140},
 {'source': 12, 'target': 15, 'value': 275},
 {'source': 12, 'target': 42, 'value': 920},
 {'source': 12, 'target': 20, 'value': 227},
 {'source': 12, 'target': 21, 'value': 84},
 {'source': 12, 'target': 44, 'value': 137},
 {'source': 12, 'target': 45, 'value': 178},
 {'source': 12, 'target': 28, 'value': 325},
 {'source': 12, 'target': 30, 'value': 89},
 {'source': 12, 'target': 46, 'value': 359},
 {'source': 12, 'target': 31, 'value': 156},
 {'source': 12, 'target': 32, 'value': 263},
 {'source': 12, 'target': 33, 'value': 155},
 {'source': 12, 'target': 43, 'value': 814},
 {'source': 12, 'target': 37, 'value': 121},
 {'source': 12, 'target': 38, 'value': 751},
 {'source': 12, 'target': 39, 'value': 95},
 {'source': 13, 'target': 3, 'value': 2540},
 {'source': 13, 'target': 5, 'value': 976},
 {'source': 13, 'target': 6, 'value': 1249},
 {'source': 13, 'target': 7, 'value': 23},
 {'source': 13, 'target': 8, 'value': 138},
 {'source': 13, 'target': 10, 'value': 67},
 {'source': 13, 'target': 15, 'value': 119},
 {'source': 13, 'target': 42, 'value': 3063},
 {'source': 13, 'target': 20, 'value': 83},
 {'source': 13, 'target': 21, 'value': 12},
 {'source': 13, 'target': 44, 'value': 82},
 {'source': 13, 'target': 45, 'value': 96},
 {'source': 13, 'target': 28, 'value': 236},
 {'source': 13, 'target': 30, 'value': 7},
 {'source': 13, 'target': 46, 'value': 204},
 {'source': 13, 'target': 31, 'value': 42},
 {'source': 13, 'target': 32, 'value': 89},
 {'source': 13, 'target': 33, 'value': 56},
 {'source': 13, 'target': 43, 'value': 1939},
 {'source': 13, 'target': 37, 'value': 21},
 {'source': 13, 'target': 38, 'value': 766},
 {'source': 13, 'target': 39, 'value': 15},
 {'source': 14, 'target': 3, 'value': 83},
 {'source': 14, 'target': 5, 'value': 52},
 {'source': 14, 'target': 6, 'value': 18},
 {'source': 14, 'target': 7, 'value': 12},
 {'source': 14, 'target': 8, 'value': 4},
 {'source': 14, 'target': 10, 'value': 5},
 {'source': 14, 'target': 15, 'value': 4},
 {'source': 14, 'target': 42, 'value': 45},
 {'source': 14, 'target': 20, 'value': 3},
 {'source': 14, 'target': 44, 'value': 4},
 {'source': 14, 'target': 45, 'value': 4},
 {'source': 14, 'target': 28, 'value': 12},
 {'source': 14, 'target': 46, 'value': 66},
 {'source': 14, 'target': 31, 'value': 11},
 {'source': 14, 'target': 32, 'value': 4},
 {'source': 14, 'target': 33, 'value': 8},
 {'source': 14, 'target': 43, 'value': 58},
 {'source': 14, 'target': 37, 'value': 4},
 {'source': 14, 'target': 38, 'value': 42},
 {'source': 14, 'target': 39, 'value': 1},
 {'source': 15, 'target': 4, 'value': 1},
 {'source': 15, 'target': 46, 'value': 8},
 {'source': 16, 'target': 42, 'value': 1},
 {'source': 16, 'target': 43, 'value': 2},
 {'source': 17, 'target': 3, 'value': 314},
 {'source': 17, 'target': 5, 'value': 69},
 {'source': 17, 'target': 6, 'value': 180},
 {'source': 17, 'target': 15, 'value': 7},
 {'source': 17, 'target': 42, 'value': 610},
 {'source': 17, 'target': 20, 'value': 2},
 {'source': 17, 'target': 44, 'value': 1},
 {'source': 17, 'target': 46, 'value': 12},
 {'source': 17, 'target': 32, 'value': 1},
 {'source': 17, 'target': 43, 'value': 1090},
 {'source': 17, 'target': 38, 'value': 66},
 {'source': 18, 'target': 3, 'value': 1834},
 {'source': 18, 'target': 5, 'value': 303},
 {'source': 18, 'target': 6, 'value': 487},
 {'source': 18, 'target': 7, 'value': 19},
 {'source': 18, 'target': 8, 'value': 51},
 {'source': 18, 'target': 10, 'value': 17},
 {'source': 18, 'target': 15, 'value': 66},
 {'source': 18, 'target': 42, 'value': 1210},
 {'source': 18, 'target': 20, 'value': 11},
 {'source': 18, 'target': 21, 'value': 2},
 {'source': 18, 'target': 44, 'value': 11},
 {'source': 18, 'target': 45, 'value': 20},
 {'source': 18, 'target': 28, 'value': 77},
 {'source': 18, 'target': 46, 'value': 158},
 {'source': 18, 'target': 31, 'value': 7},
 {'source': 18, 'target': 32, 'value': 39},
 {'source': 18, 'target': 33, 'value': 39},
 {'source': 18, 'target': 43, 'value': 237},
 {'source': 18, 'target': 37, 'value': 1},
 {'source': 18, 'target': 38, 'value': 135},
 {'source': 18, 'target': 39, 'value': 1},
 {'source': 19, 'target': 3, 'value': 1925},
 {'source': 19, 'target': 5, 'value': 875},
 {'source': 19, 'target': 6, 'value': 998},
 {'source': 19, 'target': 7, 'value': 1},
 {'source': 19, 'target': 8, 'value': 39},
 {'source': 19, 'target': 10, 'value': 28},
 {'source': 19, 'target': 15, 'value': 53},
 {'source': 19, 'target': 42, 'value': 1745},
 {'source': 19, 'target': 20, 'value': 141},
 {'source': 19, 'target': 21, 'value': 7},
 {'source': 19, 'target': 44, 'value': 37},
 {'source': 19, 'target': 45, 'value': 32},
 {'source': 19, 'target': 28, 'value': 44},
 {'source': 19, 'target': 30, 'value': 6},
 {'source': 19, 'target': 46, 'value': 112},
 {'source': 19, 'target': 31, 'value': 178},
 {'source': 19, 'target': 32, 'value': 37},
 {'source': 19, 'target': 33, 'value': 10},
 {'source': 19, 'target': 43, 'value': 643},
 {'source': 19, 'target': 37, 'value': 7},
 {'source': 19, 'target': 38, 'value': 2469},
 {'source': 19, 'target': 39, 'value': 12},
 {'source': 20, 'target': 3, 'value': 67},
 {'source': 20, 'target': 5, 'value': 54},
 {'source': 20, 'target': 6, 'value': 243},
 {'source': 20, 'target': 42, 'value': 168},
 {'source': 20, 'target': 31, 'value': 4},
 {'source': 20, 'target': 43, 'value': 62},
 {'source': 20, 'target': 38, 'value': 759},
 {'source': 21, 'target': 7, 'value': 9},
 {'source': 21, 'target': 42, 'value': 9},
 {'source': 21, 'target': 45, 'value': 1},
 {'source': 21, 'target': 32, 'value': 1},
 {'source': 21, 'target': 38, 'value': 5},
 {'source': 22, 'target': 1, 'value': 6},
 {'source': 22, 'target': 6, 'value': 4},
 {'source': 22, 'target': 8, 'value': 10},
 {'source': 22, 'target': 10, 'value': 2},
 {'source': 22, 'target': 11, 'value': 2},
 {'source': 22, 'target': 13, 'value': 2},
 {'source': 22, 'target': 15, 'value': 13},
 {'source': 22, 'target': 42, 'value': 4},
 {'source': 22, 'target': 18, 'value': 6},
 {'source': 22, 'target': 44, 'value': 2},
 {'source': 22, 'target': 22, 'value': 4},
 {'source': 22, 'target': 45, 'value': 2},
 {'source': 22, 'target': 28, 'value': 17},
 {'source': 22, 'target': 46, 'value': 24},
 {'source': 22, 'target': 32, 'value': 1},
 {'source': 22, 'target': 33, 'value': 1},
 {'source': 22, 'target': 36, 'value': 5},
 {'source': 22, 'target': 38, 'value': 1},
 {'source': 23, 'target': 3, 'value': 246},
 {'source': 23, 'target': 5, 'value': 94},
 {'source': 23, 'target': 6, 'value': 170},
 {'source': 23, 'target': 8, 'value': 1},
 {'source': 23, 'target': 42, 'value': 608},
 {'source': 23, 'target': 46, 'value': 1},
 {'source': 23, 'target': 32, 'value': 1},
 {'source': 23, 'target': 43, 'value': 52},
 {'source': 23, 'target': 38, 'value': 39},
 {'source': 24, 'target': 29, 'value': 1},
 {'source': 24, 'target': 33, 'value': 4},
 {'source': 24, 'target': 43, 'value': 6},
 {'source': 25, 'target': 3, 'value': 152},
 {'source': 25, 'target': 5, 'value': 151},
 {'source': 25, 'target': 6, 'value': 512},
 {'source': 25, 'target': 7, 'value': 3},
 {'source': 25, 'target': 8, 'value': 76},
 {'source': 25, 'target': 10, 'value': 30},
 {'source': 25, 'target': 15, 'value': 84},
 {'source': 25, 'target': 42, 'value': 1033},
 {'source': 25, 'target': 20, 'value': 8},
 {'source': 25, 'target': 21, 'value': 2},
 {'source': 25, 'target': 44, 'value': 58},
 {'source': 25, 'target': 45, 'value': 40},
 {'source': 25, 'target': 28, 'value': 91},
 {'source': 25, 'target': 46, 'value': 139},
 {'source': 25, 'target': 31, 'value': 5},
 {'source': 25, 'target': 32, 'value': 77},
 {'source': 25, 'target': 33, 'value': 29},
 {'source': 25, 'target': 43, 'value': 948},
 {'source': 25, 'target': 38, 'value': 205},
 {'source': 26, 'target': 3, 'value': 41},
 {'source': 26, 'target': 5, 'value': 47},
 {'source': 26, 'target': 6, 'value': 19},
 {'source': 26, 'target': 42, 'value': 67},
 {'source': 26, 'target': 21, 'value': 1},
 {'source': 26, 'target': 43, 'value': 115},
 {'source': 26, 'target': 38, 'value': 38},
 {'source': 27, 'target': 3, 'value': 562},
 {'source': 27, 'target': 5, 'value': 157},
 {'source': 27, 'target': 6, 'value': 507},
 {'source': 27, 'target': 7, 'value': 2},
 {'source': 27, 'target': 8, 'value': 6},
 {'source': 27, 'target': 10, 'value': 28},
 {'source': 27, 'target': 15, 'value': 10},
 {'source': 27, 'target': 42, 'value': 1567},
 {'source': 27, 'target': 44, 'value': 25},
 {'source': 27, 'target': 45, 'value': 33},
 {'source': 27, 'target': 28, 'value': 25},
 {'source': 27, 'target': 46, 'value': 39},
 {'source': 27, 'target': 31, 'value': 11},
 {'source': 27, 'target': 32, 'value': 10},
 {'source': 27, 'target': 33, 'value': 4},
 {'source': 27, 'target': 43, 'value': 1388},
 {'source': 27, 'target': 38, 'value': 313},
 {'source': 28, 'target': 3, 'value': 3},
 {'source': 28, 'target': 6, 'value': 2},
 {'source': 28, 'target': 42, 'value': 7},
 {'source': 28, 'target': 43, 'value': 7},
 {'source': 28, 'target': 38, 'value': 5},
 {'source': 29, 'target': 3, 'value': 256},
 {'source': 29, 'target': 5, 'value': 51},
 {'source': 29, 'target': 6, 'value': 33},
 {'source': 29, 'target': 7, 'value': 3},
 {'source': 29, 'target': 8, 'value': 16},
 {'source': 29, 'target': 10, 'value': 3},
 {'source': 29, 'target': 15, 'value': 14},
 {'source': 29, 'target': 42, 'value': 94},
 {'source': 29, 'target': 20, 'value': 4},
 {'source': 29, 'target': 44, 'value': 2},
 {'source': 29, 'target': 28, 'value': 18},
 {'source': 29, 'target': 46, 'value': 12},
 {'source': 29, 'target': 31, 'value': 1},
 {'source': 29, 'target': 32, 'value': 3},
 {'source': 29, 'target': 33, 'value': 4},
 {'source': 29, 'target': 43, 'value': 62},
 {'source': 29, 'target': 38, 'value': 37},
 {'source': 30, 'target': 41, 'value': 17},
 {'source': 31, 'target': 3, 'value': 1},
 {'source': 31, 'target': 42, 'value': 6},
 {'source': 31, 'target': 20, 'value': 1},
 {'source': 31, 'target': 37, 'value': 3},
 {'source': 31, 'target': 38, 'value': 2},
 {'source': 32, 'target': 3, 'value': 1},
 {'source': 32, 'target': 5, 'value': 1},
 {'source': 32, 'target': 15, 'value': 2},
 {'source': 32, 'target': 42, 'value': 2},
 {'source': 32, 'target': 37, 'value': 1},
 {'source': 32, 'target': 38, 'value': 1},
 {'source': 33, 'target': 6, 'value': 1},
 {'source': 33, 'target': 42, 'value': 5},
 {'source': 33, 'target': 43, 'value': 1},
 {'source': 34, 'target': 3, 'value': 2141},
 {'source': 34, 'target': 5, 'value': 1344},
 {'source': 34, 'target': 6, 'value': 4069},
 {'source': 34, 'target': 7, 'value': 8},
 {'source': 34, 'target': 8, 'value': 49},
 {'source': 34, 'target': 10, 'value': 23},
 {'source': 34, 'target': 15, 'value': 54},
 {'source': 34, 'target': 42, 'value': 1480},
 {'source': 34, 'target': 20, 'value': 14},
 {'source': 34, 'target': 21, 'value': 1},
 {'source': 34, 'target': 44, 'value': 9},
 {'source': 34, 'target': 45, 'value': 24},
 {'source': 34, 'target': 28, 'value': 76},
 {'source': 34, 'target': 46, 'value': 108},
 {'source': 34, 'target': 31, 'value': 3},
 {'source': 34, 'target': 32, 'value': 44},
 {'source': 34, 'target': 33, 'value': 27},
 {'source': 34, 'target': 43, 'value': 163},
 {'source': 34, 'target': 37, 'value': 1},
 {'source': 34, 'target': 38, 'value': 142},
 {'source': 34, 'target': 39, 'value': 4},
 {'source': 35, 'target': 3, 'value': 152},
 {'source': 35, 'target': 5, 'value': 243},
 {'source': 35, 'target': 6, 'value': 344},
 {'source': 35, 'target': 8, 'value': 13},
 {'source': 35, 'target': 10, 'value': 323},
 {'source': 35, 'target': 15, 'value': 25},
 {'source': 35, 'target': 42, 'value': 959},
 {'source': 35, 'target': 21, 'value': 2},
 {'source': 35, 'target': 44, 'value': 378},
 {'source': 35, 'target': 45, 'value': 298},
 {'source': 35, 'target': 28, 'value': 269},
 {'source': 35, 'target': 46, 'value': 63},
 {'source': 35, 'target': 32, 'value': 14},
 {'source': 35, 'target': 33, 'value': 10},
 {'source': 35, 'target': 43, 'value': 1408},
 {'source': 35, 'target': 37, 'value': 1},
 {'source': 35, 'target': 38, 'value': 219},
 {'source': 36, 'target': 3, 'value': 211},
 {'source': 36, 'target': 5, 'value': 174},
 {'source': 36, 'target': 6, 'value': 704},
 {'source': 36, 'target': 7, 'value': 6},
 {'source': 36, 'target': 8, 'value': 30},
 {'source': 36, 'target': 10, 'value': 5},
 {'source': 36, 'target': 15, 'value': 16},
 {'source': 36, 'target': 42, 'value': 768},
 {'source': 36, 'target': 20, 'value': 6},
 {'source': 36, 'target': 44, 'value': 5},
 {'source': 36, 'target': 45, 'value': 2},
 {'source': 36, 'target': 28, 'value': 16},
 {'source': 36, 'target': 46, 'value': 139},
 {'source': 36, 'target': 32, 'value': 14},
 {'source': 36, 'target': 33, 'value': 3},
 {'source': 36, 'target': 43, 'value': 301},
 {'source': 36, 'target': 37, 'value': 6},
 {'source': 36, 'target': 38, 'value': 241},
 {'source': 37, 'target': 42, 'value': 1},
 {'source': 37, 'target': 28, 'value': 1},
 {'source': 37, 'target': 31, 'value': 6},
 {'source': 37, 'target': 43, 'value': 2},
 {'source': 38, 'target': 7, 'value': 1},
 {'source': 38, 'target': 43, 'value': 1},
 {'source': 39, 'target': 3, 'value': 18},
 {'source': 39, 'target': 5, 'value': 11},
 {'source': 39, 'target': 6, 'value': 25},
 {'source': 39, 'target': 42, 'value': 49},
 {'source': 39, 'target': 43, 'value': 16},
 {'source': 39, 'target': 38, 'value': 4},
 {'source': 40, 'target': 3, 'value': 565},
 {'source': 40, 'target': 5, 'value': 184},
 {'source': 40, 'target': 6, 'value': 304},
 {'source': 40, 'target': 7, 'value': 18},
 {'source': 40, 'target': 8, 'value': 70},
 {'source': 40, 'target': 10, 'value': 10},
 {'source': 40, 'target': 15, 'value': 88},
 {'source': 40, 'target': 42, 'value': 2068},
 {'source': 40, 'target': 20, 'value': 10},
 {'source': 40, 'target': 44, 'value': 23},
 {'source': 40, 'target': 45, 'value': 14},
 {'source': 40, 'target': 28, 'value': 168},
 {'source': 40, 'target': 46, 'value': 190},
 {'source': 40, 'target': 31, 'value': 6},
 {'source': 40, 'target': 32, 'value': 71},
 {'source': 40, 'target': 33, 'value': 20},
 {'source': 40, 'target': 43, 'value': 806},
 {'source': 40, 'target': 37, 'value': 1},
 {'source': 40, 'target': 38, 'value': 217},
 {'source': 41, 'target': 0, 'value': 28},
 {'source': 41, 'target': 1, 'value': 6},
 {'source': 41, 'target': 2, 'value': 2},
 {'source': 41, 'target': 3, 'value': 1341},
 {'source': 41, 'target': 4, 'value': 20},

#### Create Nodes list

In [43]:
nodes_list = []

for src in unique_pu5:
    nodes_list.append({"group": group_dict.get(src), "name":src})

nodes_list

[{'group': 1, 'name': 'Australia'},
 {'group': 2, 'name': 'Austria'},
 {'group': 3, 'name': 'Belgium'},
 {'group': 4, 'name': 'Brazil'},
 {'group': 5, 'name': 'Canada'},
 {'group': 6, 'name': 'Chile'},
 {'group': 7, 'name': 'Colombia'},
 {'group': 8, 'name': 'Cyprus'},
 {'group': 9, 'name': 'Czech Republic'},
 {'group': 10, 'name': 'Denmark'},
 {'group': 11, 'name': 'Estonia'},
 {'group': 12, 'name': 'Finland'},
 {'group': 13, 'name': 'France'},
 {'group': 14, 'name': 'Germany'},
 {'group': 15, 'name': 'Greece'},
 {'group': 16, 'name': 'Hungary'},
 {'group': 17, 'name': 'Iceland'},
 {'group': 18, 'name': 'Ireland'},
 {'group': 19, 'name': 'Italy'},
 {'group': 20, 'name': 'Japan'},
 {'group': 21, 'name': 'Korea'},
 {'group': 22, 'name': 'Kuwait'},
 {'group': 23, 'name': 'Liechtenstein'},
 {'group': 24, 'name': 'Luxembourg'},
 {'group': 25, 'name': 'Monaco'},
 {'group': 26, 'name': 'Netherlands'},
 {'group': 27, 'name': 'New Zealand'},
 {'group': 28, 'name': 'Norway'},
 {'group': 29, 'name': 'Poland'},
 {'group': 30, 'name': 'Portugal'},
 {'group': 31, 'name': 'Qatar'},
 {'group': 32, 'name': 'Saudi Arabia'},
 {'group': 33, 'name': 'Slovak Republic'},
 {'group': 34, 'name': 'Slovenia'},
 {'group': 35, 'name': 'Spain'},
 {'group': 36, 'name': 'Sweden'},
 {'group': 37, 'name': 'Switzerland'},
 {'group': 38, 'name': 'Taiwan'},
 {'group': 39, 'name': 'Thailand'},
 {'group': 40, 'name': 'United Arab Emirates'},
 {'group': 41, 'name': 'United Kingdom'},
 {'group': 42, 'name': 'United States'},
 {'group': 43, 'name': 'India'},
 {'group': 44, 'name': 'South Africa'},
 {'group': 45, 'name': 'Latvia'},
 {'group': 46, 'name': 'Lithuania'},
 {'group': 47, 'name': 'Romania'}]

#### Create JSON file

In [46]:
json_prep = {"nodes":nodes_list, "links":links_list}
json_dump = json.dumps(json_prep, indent=1, sort_keys=True)
print(json_dump)

{
 "links": [
  {
   "source": 0,
   "target": 3,
   "value": 97
  },
  {
   "source": 0,
   "target": 5,
   "value": 109
  },
  {
   "source": 0,
   "target": 6,
   "value": 95
  },
  {
   "source": 0,
   "target": 7,
   "value": 6
  },
  {
   "source": 0,
   "target": 8,
   "value": 1
  },
  {
   "source": 0,
   "target": 15,
   "value": 6
  },
  {
   "source": 0,
   "target": 42,
   "value": 991
  },
  {
   "source": 0,
   "target": 20,
   "value": 37
  },
  {
   "source": 0,
   "target": 28,
   "value": 1
  },
  {
   "source": 0,
   "target": 31,
   "value": 1
  },
  {
   "source": 0,
   "target": 33,
   "value": 3
  },
  {
   "source": 0,
   "target": 43,
   "value": 393
  },
  {
   "source": 0,
   "target": 37,
   "value": 11
  },
  {
   "source": 0,
   "target": 38,
   "value": 1035
  },
  {
   "source": 1,
   "target": 3,
   "value": 519
  },
  {
   "source": 1,
   "target": 5,
   "value": 66
  },
  {
   "source": 1,
   "target": 6,
   "value": 108
  },
  {
   "source": 1,
   "target": 7,
   "value": 10
  },
  {
   "source": 1,
   "target": 8,
   "value": 80
  },
  {
   "source": 1,
   "target": 10,
   "value": 20
  },
  {
   "source": 1,
   "target": 15,
   "value": 79
  },
  {
   "source": 1,
   "target": 42,
   "value": 283
  },
  {
   "source": 1,
   "target": 20,
   "value": 14
  },
  {
   "source": 1,
   "target": 21,
   "value": 3
  },
  {
   "source": 1,
   "target": 44,
   "value": 14
  },
  {
   "source": 1,
   "target": 45,
   "value": 29
  },
  {
   "source": 1,
   "target": 28,
   "value": 44
  },
  {
   "source": 1,
   "target": 46,
   "value": 154
  },
  {
   "source": 1,
   "target": 31,
   "value": 15
  },
  {
   "source": 1,
   "target": 32,
   "value": 81
  },
  {
   "source": 1,
   "target": 33,
   "value": 65
  },
  {
   "source": 1,
   "target": 43,
   "value": 253
  },
  {
   "source": 1,
   "target": 37,
   "value": 18
  },
  {
   "source": 1,
   "target": 38,
   "value": 85
  },
  {
   "source": 1,
   "target": 39,
   "value": 4
  },
  {
   "source": 2,
   "target": 3,
   "value": 894
  },
  {
   "source": 2,
   "target": 5,
   "value": 545
  },
  {
   "source": 2,
   "target": 6,
   "value": 573
  },
  {
   "source": 2,
   "target": 7,
   "value": 1
  },
  {
   "source": 2,
   "target": 8,
   "value": 10
  },
  {
   "source": 2,
   "target": 10,
   "value": 5
  },
  {
   "source": 2,
   "target": 15,
   "value": 15
  },
  {
   "source": 2,
   "target": 42,
   "value": 1126
  },
  {
   "source": 2,
   "target": 20,
   "value": 4
  },
  {
   "source": 2,
   "target": 44,
   "value": 4
  },
  {
   "source": 2,
   "target": 45,
   "value": 8
  },
  {
   "source": 2,
   "target": 28,
   "value": 24
  },
  {
   "source": 2,
   "target": 46,
   "value": 33
  },
  {
   "source": 2,
   "target": 31,
   "value": 1
  },
  {
   "source": 2,
   "target": 32,
   "value": 12
  },
  {
   "source": 2,
   "target": 33,
   "value": 10
  },
  {
   "source": 2,
   "target": 43,
   "value": 1261
  },
  {
   "source": 2,
   "target": 37,
   "value": 15
  },
  {
   "source": 2,
   "target": 38,
   "value": 223
  },
  {
   "source": 3,
   "target": 5,
   "value": 1
  },
  {
   "source": 3,
   "target": 6,
   "value": 22
  },
  {
   "source": 3,
   "target": 12,
   "value": 1
  },
  {
   "source": 3,
   "target": 19,
   "value": 1
  },
  {
   "source": 3,
   "target": 31,
   "value": 1
  },
  {
   "source": 3,
   "target": 43,
   "value": 4
  },
  {
   "source": 4,
   "target": 3,
   "value": 583
  },
  {
   "source": 4,
   "target": 5,
   "value": 375
  },
  {
   "source": 4,
   "target": 6,
   "value": 852
  },
  {
   "source": 4,
   "target": 7,
   "value": 7
  },
  {
   "source": 4,
   "target": 8,
   "value": 47
  },
  {
   "source": 4,
   "target": 10,
   "value": 11
  },
  {
   "source": 4,
   "target": 15,
   "value": 41
  },
  {
   "source": 4,
   "target": 42,
   "value": 1202
  },
  {
   "source": 4,
   "target": 20,
   "value": 18
  },
  {
   "source": 4,
   "target": 21,
   "value": 1
  },
  {
   "source": 4,
   "target": 44,
   "value": 14
  },
  {
   "source": 4,
   "target": 45,
   "value": 25
  },
  {
   "source": 4,
   "target": 28,
   "value": 87
  },
  {
   "source": 4,
   "target": 46,
   "value": 67
  },
  {
   "source": 4,
   "target": 31,
   "value": 2
  },
  {
   "source": 4,
   "target": 32,
   "value": 49
  },
  {
   "source": 4,
   "target": 33,
   "value": 9
  },
  {
   "source": 4,
   "target": 43,
   "value": 670
  },
  {
   "source": 4,
   "target": 38,
   "value": 465
  },
  {
   "source": 5,
   "target": 3,
   "value": 5
  },
  {
   "source": 5,
   "target": 5,
   "value": 1
  },
  {
   "source": 5,
   "target": 6,
   "value": 43
  },
  {
   "source": 5,
   "target": 41,
   "value": 1
  },
  {
   "source": 6,
   "target": 5,
   "value": 17
  },
  {
   "source": 6,
   "target": 6,
   "value": 1
  },
  {
   "source": 6,
   "target": 38,
   "value": 1
  },
  {
   "source": 6,
   "target": 41,
   "value": 1
  },
  {
   "source": 7,
   "target": 42,
   "value": 1
  },
  {
   "source": 8,
   "target": 3,
   "value": 3
  },
  {
   "source": 8,
   "target": 5,
   "value": 3
  },
  {
   "source": 8,
   "target": 6,
   "value": 3
  },
  {
   "source": 8,
   "target": 10,
   "value": 1
  },
  {
   "source": 8,
   "target": 42,
   "value": 10
  },
  {
   "source": 8,
   "target": 44,
   "value": 2
  },
  {
   "source": 8,
   "target": 45,
   "value": 4
  },
  {
   "source": 8,
   "target": 46,
   "value": 2
  },
  {
   "source": 8,
   "target": 32,
   "value": 1
  },
  {
   "source": 8,
   "target": 43,
   "value": 2
  },
  {
   "source": 8,
   "target": 38,
   "value": 3
  },
  {
   "source": 9,
   "target": 3,
   "value": 3
  },
  {
   "source": 9,
   "target": 5,
   "value": 15
  },
  {
   "source": 9,
   "target": 6,
   "value": 7
  },
  {
   "source": 9,
   "target": 42,
   "value": 381
  },
  {
   "source": 9,
   "target": 43,
   "value": 359
  },
  {
   "source": 9,
   "target": 38,
   "value": 160
  },
  {
   "source": 9,
   "target": 39,
   "value": 5
  },
  {
   "source": 10,
   "target": 8,
   "value": 1
  },
  {
   "source": 10,
   "target": 42,
   "value": 1
  },
  {
   "source": 10,
   "target": 28,
   "value": 1
  },
  {
   "source": 11,
   "target": 3,
   "value": 139
  },
  {
   "source": 11,
   "target": 5,
   "value": 78
  },
  {
   "source": 11,
   "target": 6,
   "value": 89
  },
  {
   "source": 11,
   "target": 8,
   "value": 2
  },
  {
   "source": 11,
   "target": 10,
   "value": 84
  },
  {
   "source": 11,
   "target": 15,
   "value": 5
  },
  {
   "source": 11,
   "target": 42,
   "value": 463
  },
  {
   "source": 11,
   "target": 44,
   "value": 49
  },
  {
   "source": 11,
   "target": 45,
   "value": 33
  },
  {
   "source": 11,
   "target": 28,
   "value": 11
  },
  {
   "source": 11,
   "target": 46,
   "value": 1
  },
  {
   "source": 11,
   "target": 31,
   "value": 1
  },
  {
   "source": 11,
   "target": 32,
   "value": 1
  },
  {
   "source": 11,
   "target": 43,
   "value": 266
  },
  {
   "source": 11,
   "target": 38,
   "value": 137
  },
  {
   "source": 12,
   "target": 3,
   "value": 1157
  },
  {
   "source": 12,
   "target": 5,
   "value": 670
  },
  {
   "source": 12,
   "target": 6,
   "value": 491
  },
  {
   "source": 12,
   "target": 7,
   "value": 116
  },
  {
   "source": 12,
   "target": 8,
   "value": 327
  },
  {
   "source": 12,
   "target": 10,
   "value": 140
  },
  {
   "source": 12,
   "target": 15,
   "value": 275
  },
  {
   "source": 12,
   "target": 42,
   "value": 920
  },
  {
   "source": 12,
   "target": 20,
   "value": 227
  },
  {
   "source": 12,
   "target": 21,
   "value": 84
  },
  {
   "source": 12,
   "target": 44,
   "value": 137
  },
  {
   "source": 12,
   "target": 45,
   "value": 178
  },
  {
   "source": 12,
   "target": 28,
   "value": 325
  },
  {
   "source": 12,
   "target": 30,
   "value": 89
  },
  {
   "source": 12,
   "target": 46,
   "value": 359
  },
  {
   "source": 12,
   "target": 31,
   "value": 156
  },
  {
   "source": 12,
   "target": 32,
   "value": 263
  },
  {
   "source": 12,
   "target": 33,
   "value": 155
  },
  {
   "source": 12,
   "target": 43,
   "value": 814
  },
  {
   "source": 12,
   "target": 37,
   "value": 121
  },
  {
   "source": 12,
   "target": 38,
   "value": 751
  },
  {
   "source": 12,
   "target": 39,
   "value": 95
  },
  {
   "source": 13,
   "target": 3,
   "value": 2540
  },
  {
   "source": 13,
   "target": 5,
   "value": 976
  },
  {
   "source": 13,
   "target": 6,
   "value": 1249
  },
  {
   "source": 13,
   "target": 7,
   "value": 23
  },
  {
   "source": 13,
   "target": 8,
   "value": 138
  },
  {
   "source": 13,
   "target": 10,
   "value": 67
  },
  {
   "source": 13,
   "target": 15,
   "value": 119
  },
  {
   "source": 13,
   "target": 42,
   "value": 3063
  },
  {
   "source": 13,
   "target": 20,
   "value": 83
  },
  {
   "source": 13,
   "target": 21,
   "value": 12
  },
  {
   "source": 13,
   "target": 44,
   "value": 82
  },
  {
   "source": 13,
   "target": 45,
   "value": 96
  },
  {
   "source": 13,
   "target": 28,
   "value": 236
  },
  {
   "source": 13,
   "target": 30,
   "value": 7
  },
  {
   "source": 13,
   "target": 46,
   "value": 204
  },
  {
   "source": 13,
   "target": 31,
   "value": 42
  },
  {
   "source": 13,
   "target": 32,
   "value": 89
  },
  {
   "source": 13,
   "target": 33,
   "value": 56
  },
  {
   "source": 13,
   "target": 43,
   "value": 1939
  },
  {
   "source": 13,
   "target": 37,
   "value": 21
  },
  {
   "source": 13,
   "target": 38,
   "value": 766
  },
  {
   "source": 13,
   "target": 39,
   "value": 15
  },
  {
   "source": 14,
   "target": 3,
   "value": 83
  },
  {
   "source": 14,
   "target": 5,
   "value": 52
  },
  {
   "source": 14,
   "target": 6,
   "value": 18
  },
  {
   "source": 14,
   "target": 7,
   "value": 12
  },
  {
   "source": 14,
   "target": 8,
   "value": 4
  },
  {
   "source": 14,
   "target": 10,
   "value": 5
  },
  {
   "source": 14,
   "target": 15,
   "value": 4
  },
  {
   "source": 14,
   "target": 42,
   "value": 45
  },
  {
   "source": 14,
   "target": 20,
   "value": 3
  },
  {
   "source": 14,
   "target": 44,
   "value": 4
  },
  {
   "source": 14,
   "target": 45,
   "value": 4
  },
  {
   "source": 14,
   "target": 28,
   "value": 12
  },
  {
   "source": 14,
   "target": 46,
   "value": 66
  },
  {
   "source": 14,
   "target": 31,
   "value": 11
  },
  {
   "source": 14,
   "target": 32,
   "value": 4
  },
  {
   "source": 14,
   "target": 33,
   "value": 8
  },
  {
   "source": 14,
   "target": 43,
   "value": 58
  },
  {
   "source": 14,
   "target": 37,
   "value": 4
  },
  {
   "source": 14,
   "target": 38,
   "value": 42
  },
  {
   "source": 14,
   "target": 39,
   "value": 1
  },
  {
   "source": 15,
   "target": 4,
   "value": 1
  },
  {
   "source": 15,
   "target": 46,
   "value": 8
  },
  {
   "source": 16,
   "target": 42,
   "value": 1
  },
  {
   "source": 16,
   "target": 43,
   "value": 2
  },
  {
   "source": 17,
   "target": 3,
   "value": 314
  },
  {
   "source": 17,
   "target": 5,
   "value": 69
  },
  {
   "source": 17,
   "target": 6,
   "value": 180
  },
  {
   "source": 17,
   "target": 15,
   "value": 7
  },
  {
   "source": 17,
   "target": 42,
   "value": 610
  },
  {
   "source": 17,
   "target": 20,
   "value": 2
  },
  {
   "source": 17,
   "target": 44,
   "value": 1
  },
  {
   "source": 17,
   "target": 46,
   "value": 12
  },
  {
   "source": 17,
   "target": 32,
   "value": 1
  },
  {
   "source": 17,
   "target": 43,
   "value": 1090
  },
  {
   "source": 17,
   "target": 38,
   "value": 66
  },
  {
   "source": 18,
   "target": 3,
   "value": 1834
  },
  {
   "source": 18,
   "target": 5,
   "value": 303
  },
  {
   "source": 18,
   "target": 6,
   "value": 487
  },
  {
   "source": 18,
   "target": 7,
   "value": 19
  },
  {
   "source": 18,
   "target": 8,
   "value": 51
  },
  {
   "source": 18,
   "target": 10,
   "value": 17
  },
  {
   "source": 18,
   "target": 15,
   "value": 66
  },
  {
   "source": 18,
   "target": 42,
   "value": 1210
  },
  {
   "source": 18,
   "target": 20,
   "value": 11
  },
  {
   "source": 18,
   "target": 21,
   "value": 2
  },
  {
   "source": 18,
   "target": 44,
   "value": 11
  },
  {
   "source": 18,
   "target": 45,
   "value": 20
  },
  {
   "source": 18,
   "target": 28,
   "value": 77
  },
  {
   "source": 18,
   "target": 46,
   "value": 158
  },
  {
   "source": 18,
   "target": 31,
   "value": 7
  },
  {
   "source": 18,
   "target": 32,
   "value": 39
  },
  {
   "source": 18,
   "target": 33,
   "value": 39
  },
  {
   "source": 18,
   "target": 43,
   "value": 237
  },
  {
   "source": 18,
   "target": 37,
   "value": 1
  },
  {
   "source": 18,
   "target": 38,
   "value": 135
  },
  {
   "source": 18,
   "target": 39,
   "value": 1
  },
  {
   "source": 19,
   "target": 3,
   "value": 1925
  },
  {
   "source": 19,
   "target": 5,
   "value": 875
  },
  {
   "source": 19,
   "target": 6,
   "value": 998
  },
  {
   "source": 19,
   "target": 7,
   "value": 1
  },
  {
   "source": 19,
   "target": 8,
   "value": 39
  },
  {
   "source": 19,
   "target": 10,
   "value": 28
  },
  {
   "source": 19,
   "target": 15,
   "value": 53
  },
  {
   "source": 19,
   "target": 42,
   "value": 1745
  },
  {
   "source": 19,
   "target": 20,
   "value": 141
  },
  {
   "source": 19,
   "target": 21,
   "value": 7
  },
  {
   "source": 19,
   "target": 44,
   "value": 37
  },
  {
   "source": 19,
   "target": 45,
   "value": 32
  },
  {
   "source": 19,
   "target": 28,
   "value": 44
  },
  {
   "source": 19,
   "target": 30,
   "value": 6
  },
  {
   "source": 19,
   "target": 46,
   "value": 112
  },
  {
   "source": 19,
   "target": 31,
   "value": 178
  },
  {
   "source": 19,
   "target": 32,
   "value": 37
  },
  {
   "source": 19,
   "target": 33,
   "value": 10
  },
  {
   "source": 19,
   "target": 43,
   "value": 643
  },
  {
   "source": 19,
   "target": 37,
   "value": 7
  },
  {
   "source": 19,
   "target": 38,
   "value": 2469
  },
  {
   "source": 19,
   "target": 39,
   "value": 12
  },
  {
   "source": 20,
   "target": 3,
   "value": 67
  },
  {
   "source": 20,
   "target": 5,
   "value": 54
  },
  {
   "source": 20,
   "target": 6,
   "value": 243
  },
  {
   "source": 20,
   "target": 42,
   "value": 168
  },
  {
   "source": 20,
   "target": 31,
   "value": 4
  },
  {
   "source": 20,
   "target": 43,
   "value": 62
  },
  {
   "source": 20,
   "target": 38,
   "value": 759
  },
  {
   "source": 21,
   "target": 7,
   "value": 9
  },
  {
   "source": 21,
   "target": 42,
   "value": 9
  },
  {
   "source": 21,
   "target": 45,
   "value": 1
  },
  {
   "source": 21,
   "target": 32,
   "value": 1
  },
  {
   "source": 21,
   "target": 38,
   "value": 5
  },
  {
   "source": 22,
   "target": 1,
   "value": 6
  },
  {
   "source": 22,
   "target": 6,
   "value": 4
  },
  {
   "source": 22,
   "target": 8,
   "value": 10
  },
  {
   "source": 22,
   "target": 10,
   "value": 2
  },
  {
   "source": 22,
   "target": 11,
   "value": 2
  },
  {
   "source": 22,
   "target": 13,
   "value": 2
  },
  {
   "source": 22,
   "target": 15,
   "value": 13
  },
  {
   "source": 22,
   "target": 42,
   "value": 4
  },
  {
   "source": 22,
   "target": 18,
   "value": 6
  },
  {
   "source": 22,
   "target": 44,
   "value": 2
  },
  {
   "source": 22,
   "target": 22,
   "value": 4
  },
  {
   "source": 22,
   "target": 45,
   "value": 2
  },
  {
   "source": 22,
   "target": 28,
   "value": 17
  },
  {
   "source": 22,
   "target": 46,
   "value": 24
  },
  {
   "source": 22,
   "target": 32,
   "value": 1
  },
  {
   "source": 22,
   "target": 33,
   "value": 1
  },
  {
   "source": 22,
   "target": 36,
   "value": 5
  },
  {
   "source": 22,
   "target": 38,
   "value": 1
  },
  {
   "source": 23,
   "target": 3,
   "value": 246
  },
  {
   "source": 23,
   "target": 5,
   "value": 94
  },
  {
   "source": 23,
   "target": 6,
   "value": 170
  },
  {
   "source": 23,
   "target": 8,
   "value": 1
  },
  {
   "source": 23,
   "target": 42,
   "value": 608
  },
  {
   "source": 23,
   "target": 46,
   "value": 1
  },
  {
   "source": 23,
   "target": 32,
   "value": 1
  },
  {
   "source": 23,
   "target": 43,
   "value": 52
  },
  {
   "source": 23,
   "target": 38,
   "value": 39
  },
  {
   "source": 24,
   "target": 29,
   "value": 1
  },
  {
   "source": 24,
   "target": 33,
   "value": 4
  },
  {
   "source": 24,
   "target": 43,
   "value": 6
  },
  {
   "source": 25,
   "target": 3,
   "value": 152
  },
  {
   "source": 25,
   "target": 5,
   "value": 151
  },
  {
   "source": 25,
   "target": 6,
   "value": 512
  },
  {
   "source": 25,
   "target": 7,
   "value": 3
  },
  {
   "source": 25,
   "target": 8,
   "value": 76
  },
  {
   "source": 25,
   "target": 10,
   "value": 30
  },
  {
   "source": 25,
   "target": 15,
   "value": 84
  },
  {
   "source": 25,
   "target": 42,
   "value": 1033
  },
  {
   "source": 25,
   "target": 20,
   "value": 8
  },
  {
   "source": 25,
   "target": 21,
   "value": 2
  },
  {
   "source": 25,
   "target": 44,
   "value": 58
  },
  {
   "source": 25,
   "target": 45,
   "value": 40
  },
  {
   "source": 25,
   "target": 28,
   "value": 91
  },
  {
   "source": 25,
   "target": 46,
   "value": 139
  },
  {
   "source": 25,
   "target": 31,
   "value": 5
  },
  {
   "source": 25,
   "target": 32,
   "value": 77
  },
  {
   "source": 25,
   "target": 33,
   "value": 29
  },
  {
   "source": 25,
   "target": 43,
   "value": 948
  },
  {
   "source": 25,
   "target": 38,
   "value": 205
  },
  {
   "source": 26,
   "target": 3,
   "value": 41
  },
  {
   "source": 26,
   "target": 5,
   "value": 47
  },
  {
   "source": 26,
   "target": 6,
   "value": 19
  },
  {
   "source": 26,
   "target": 42,
   "value": 67
  },
  {
   "source": 26,
   "target": 21,
   "value": 1
  },
  {
   "source": 26,
   "target": 43,
   "value": 115
  },
  {
   "source": 26,
   "target": 38,
   "value": 38
  },
  {
   "source": 27,
   "target": 3,
   "value": 562
  },
  {
   "source": 27,
   "target": 5,
   "value": 157
  },
  {
   "source": 27,
   "target": 6,
   "value": 507
  },
  {
   "source": 27,
   "target": 7,
   "value": 2
  },
  {
   "source": 27,
   "target": 8,
   "value": 6
  },
  {
   "source": 27,
   "target": 10,
   "value": 28
  },
  {
   "source": 27,
   "target": 15,
   "value": 10
  },
  {
   "source": 27,
   "target": 42,
   "value": 1567
  },
  {
   "source": 27,
   "target": 44,
   "value": 25
  },
  {
   "source": 27,
   "target": 45,
   "value": 33
  },
  {
   "source": 27,
   "target": 28,
   "value": 25
  },
  {
   "source": 27,
   "target": 46,
   "value": 39
  },
  {
   "source": 27,
   "target": 31,
   "value": 11
  },
  {
   "source": 27,
   "target": 32,
   "value": 10
  },
  {
   "source": 27,
   "target": 33,
   "value": 4
  },
  {
   "source": 27,
   "target": 43,
   "value": 1388
  },
  {
   "source": 27,
   "target": 38,
   "value": 313
  },
  {
   "source": 28,
   "target": 3,
   "value": 3
  },
  {
   "source": 28,
   "target": 6,
   "value": 2
  },
  {
   "source": 28,
   "target": 42,
   "value": 7
  },
  {
   "source": 28,
   "target": 43,
   "value": 7
  },
  {
   "source": 28,
   "target": 38,
   "value": 5
  },
  {
   "source": 29,
   "target": 3,
   "value": 256
  },
  {
   "source": 29,
   "target": 5,
   "value": 51
  },
  {
   "source": 29,
   "target": 6,
   "value": 33
  },
  {
   "source": 29,
   "target": 7,
   "value": 3
  },
  {
   "source": 29,
   "target": 8,
   "value": 16
  },
  {
   "source": 29,
   "target": 10,
   "value": 3
  },
  {
   "source": 29,
   "target": 15,
   "value": 14
  },
  {
   "source": 29,
   "target": 42,
   "value": 94
  },
  {
   "source": 29,
   "target": 20,
   "value": 4
  },
  {
   "source": 29,
   "target": 44,
   "value": 2
  },
  {
   "source": 29,
   "target": 28,
   "value": 18
  },
  {
   "source": 29,
   "target": 46,
   "value": 12
  },
  {

#### Dump into JSON file

In [47]:
filename_out = 'purpose.json'
json_out = open(filename_out,'w')
json_out.write(json_dump)
json_out.close()

In [7]:
purposes5 = purpamt5[['coalesced_purpose_name']]
# purposes
purplist5 = purposes5.values.tolist()
purplist5

[['Air transport'],
 ['Rail transport'],
 ['Industrial development'],
 ['RESCHEDULING AND REFINANCING'],
 ['Power generation/non-renewable sources']]

In [4]:
kiwi = pd.read_csv('kiwi-donations.csv', delimiter=',')
kiwi

    year     recipient     amount
0   1981         India   752775.0
1   1982      Thailand   572352.0
2   1983      Thailand   216892.0
3   1985      Thailand  4831732.0
4   1995         Chile   273712.0
5   1995         India   224051.0
6   1995  South Africa   983977.0
7   1995      Thailand    69294.0
8   2002        Brazil   214401.0
9   2002         Chile   296078.0
10  2002      Colombia   365547.0
11  2002         India  1083306.0
12  2002  South Africa  1745946.0
13  2002      Thailand   260043.0
14  2003        Brazil   260058.0
15  2003         Chile   567339.0
16  2003      Colombia   190786.0
17  2003         India  1798947.0
18  2003  South Africa  2009242.0
19  2003      Thailand   603022.0
20  2004        Brazil   278870.0
21  2004         Chile   479085.0
22  2004      Colombia   221659.0
23  2004         India  1720453.0
24  2004        Kuwait   153669.0
25  2004  South Africa  2303984.0
26  2004      Thailand   185190.0
27  2005        Brazil   293576.0
28  2005         Chile   472997.0
29  2005      Colombia   113277.0
..   ...           ...        ...
48  2008         India  1953889.0
49  2008  South Africa  1621520.0
50  2008      Thailand   373331.0
51  2009        Brazil   339120.0
52  2009         Chile   433699.0
53  2009         India  2579805.0
54  2009  South Africa  1270041.0
55  2009      Thailand    97634.0
56  2010        Brazil   284989.0
57  2010         Chile  1513698.0
58  2010      Colombia   109110.0
59  2010         India   408698.0
60  2010  South Africa  1198622.0
61  2010      Thailand     3829.0
62  2011        Brazil   212413.0
63  2011         Chile   278743.0
64  2011         India  1640241.0
65  2011  South Africa  1350266.0
66  2011      Thailand   142135.0
67  2012        Brazil    97067.0
68  2012         Chile  1464630.0
69  2012      Colombia    11260.0
70  2012         India    33970.0
71  2012  South Africa   115737.0
72  2013        Brazil   133652.0
73  2013         Chile   319376.0
74  2013      Colombia   244739.0
75  2013         India   962568.0
76  2013  South Africa   217244.0
77  2013      Thailand    60751.0

[78 rows x 3 columns]

In [5]:
kiwi['amount'].max()

4831732.0

In [48]:
p = pd.read_csv('purp.csv')
p

,year,coalesced_purpose_name,commitment_amount_usd_constant
0,1973,Advanced tech. & managerial training,1.762669e+07
1,1973,Advanced technical and managerial training,7.958320e+05
2,1973,Agricultural development,2.248132e+08
3,1973,Agricultural education/training,2.210626e+06
4,1973,Agricultural inputs,4.065039e+08
5,1973,Agricultural land resources,2.141171e+06
6,1973,Agricultural research,1.339137e+06
7,1973,"Agricultural services, purpose",6.023040e+07
8,1973,Agricultural water resources,4.017412e+06
9,1973,"Agriculture, purpose unspecified or does not f...",1.555871e+08
10,1973,Basic health infrastructure,5.689529e+07
11,1973,Debt forgiveness,4.103104e+07
12,1973,Education facilities and training,3.704400e+07
13,1973,Education policy & admin. management,1.008103e+08
14,1973,Electrical transmission/distribution,5.138609e+07
15,1973,Family planning,1.109148e+07
16,1973,Fishing Development,1.755675e+06
17,1973,Food security programmes/food aid,4.698684e+08
18,1973,Forestry development,1.497040e+05
19,1973,Formal sector financial intermediaries,3.072338e+07
20,1973,General budget support,3.592756e+08
21,1973,Government administration,1.603750e+07
22,1973,Health policy & admin. management,1.088751e+08
23,1973,Health policy and administrative management,6.311440e+05
24,1973,Higher education,2.144315e+06
25,1973,Import support (capital goods),2.918863e+08
26,1973,Import support (commodities),1.000538e+09
27,1973,Industrial development,2.007764e+08
28,1973,Industrial policy & admin. mgmt,1.169849e+08
29,1973,Material relief assistance and services,7.154240e+05
...,...,...,...
6051,2013,Small and medium-sized enterprises (SME) devel...,8.435044e+06
6052,2013,Social/ welfare services,7.688384e+07
6053,2013,Std control including hiv/aids,5.886570e+05
6054,2013,Strengthening civil society,1.375120e+08
6055,2013,Support to international NGOs,5.945100e+04
6056,2013,Support to national NGOs,1.570553e+06
6057,2013,Teacher training,1.794858e+07
6058,2013,Technological research and development,1.468792e+06
6059,2013,Telecommunications,5.520572e+06
6060,2013,Tourism policy and admin. management,9.925400e+04
6061,2013,Tourism policy and administrative management,2.822417e+06
6062,2013,Trade education/training,8.430200e+04
6063,2013,Trade facilitation,1.724840e+07
6064,2013,Trade policy and administrative management,1.227480e+05
6065,2013,"Transport and Storage, combination of purposes",2.511958e+08
6066,2013,Transport policy and administrative management,3.657212e+06
6067,2013,Tuberculosis control,1.291000e+03
6068,2013,Urban development and management,2.963654e+08
6069,2013,Vocational training,1.321891e+07
6070,2013,Waste management/disposal,9.104440e+05
6071,2013,Water Research,3.289320e+05
6072,2013,"Water Supply and Sanitation, combination of pu...",1.727000e+03
6073,2013,"Water Supply and Sanitation, purpose unspecifi...",1.770250e+07
6074,2013,Water resources policy and administrative mana...,5.681210e+06
6075,2013,Water resources policy/admin. mgmt,6.325090e+05
6076,2013,Water resources protection,8.120160e+06
6077,2013,Water supply and sanitation - large systems,1.482226e+08
6078,2013,Water transport,1.313320e+05
6079,2013,Women in development,2.258785e+06
6080,2013,Women's equality organisations and institutions,1.954070e+05

In [34]:
p['commitment_amount_usd_constant'].max()

8344866729.0

In [54]:
# p = p.loc[p['coalesced_purpose_name'] == [['Air transport','Rail transport','Industrial development','RESCHEDULING AND REFINANCING','Power generation/non-renewable sources','Import support (capital goods)','Social/ welfare services','Power generation/renewable sources','Telecommunications','Mineral/Metal prospection and exploration']]]
#q = p.loc[p['coalesced_purpose_name'] == 'Rail transport']
q = p.loc[p['coalesced_purpose_name'].isin(['Rail transport','Air transport','Industrial development','RESCHEDULING AND REFINANCING','Power generation/non-renewable sources','Import support (capital goods)','Social/ welfare services','Power generation/renewable sources','Telecommunications','Mineral/Metal prospection and exploration'])]
q

,year,coalesced_purpose_name,commitment_amount_usd_constant
25,1973,Import support (capital goods),2.918863e+08
27,1973,Industrial development,2.007764e+08
32,1973,Power generation/non-renewable sources,2.782567e+07
34,1973,Rail transport,9.579263e+07
41,1973,Telecommunications,2.051220e+08
57,1974,Air transport,1.525672e+07
76,1974,Import support (capital goods),2.271941e+08
78,1974,Industrial development,1.539951e+08
81,1974,Mineral/Metal prospection and exploration,5.135311e+06
84,1974,Power generation/non-renewable sources,3.988053e+07
85,1974,Power generation/renewable sources,1.248614e+08
87,1974,Rail transport,4.256376e+07
95,1974,Telecommunications,1.804753e+08
109,1975,Air transport,1.582943e+07
124,1975,Import support (capital goods),2.826322e+08
126,1975,Industrial development,1.307039e+08
129,1975,Mineral/Metal prospection and exploration,1.184111e+07
131,1975,Power generation/non-renewable sources,3.316643e+07
132,1975,Rail transport,6.008068e+07
139,1975,Telecommunications,3.316643e+07
178,1976,Import support (capital goods),1.545160e+08
180,1976,Industrial development,1.444037e+08
184,1976,Mineral/Metal prospection and exploration,4.699400e+04
186,1976,Power generation/renewable sources,2.585004e+08
188,1976,Rail transport,6.585999e+07
193,1976,Social/ welfare services,2.219382e+07
194,1976,Telecommunications,1.012682e+08
208,1977,Air transport,7.046280e+05
229,1977,Import support (capital goods),2.535563e+08
231,1977,Industrial development,3.525237e+08
...,...,...,...
5399,2010,Industrial development,7.839952e+07
5437,2010,Power generation/non-renewable sources,1.612781e+06
5438,2010,Power generation/renewable sources,1.784257e+08
5446,2010,Rail transport,2.769999e+09
5469,2010,Social/ welfare services,2.597157e+08
5479,2010,Telecommunications,2.591233e+06
5518,2011,Air transport,4.105579e+06
5606,2011,Industrial development,1.517346e+07
5621,2011,Mineral/Metal prospection and exploration,1.217712e+06
5635,2011,Power generation/non-renewable sources,2.009480e+05
5636,2011,Power generation/renewable sources,1.036425e+09
5643,2011,Rail transport,4.367780e+08
5660,2011,Social/ welfare services,1.225644e+08
5670,2011,Telecommunications,7.745790e+05
5711,2012,Air transport,4.390228e+06
5803,2012,Industrial development,2.569208e+06
5821,2012,Mineral/Metal prospection and exploration,5.455700e+05
5838,2012,Power generation/non-renewable sources,4.959152e+07
5839,2012,Power generation/renewable sources,3.759925e+08
5847,2012,Rail transport,1.619977e+09
5867,2012,Social/ welfare services,6.853119e+07
5879,2012,Telecommunications,1.611860e+06
5919,2013,Air transport,5.627464e+06
5998,2013,Industrial development,4.937413e+06
6015,2013,Mineral/Metal prospection and exploration,2.839501e+06
6028,2013,Power generation/non-renewable sources,2.508385e+08
6029,2013,Power generation/renewable sources,3.362385e+08
6036,2013,Rail transport,2.251372e+09
6052,2013,Social/ welfare services,7.688384e+07
6059,2013,Telecommunications,5.520572e+06

In [55]:
q.to_csv(r'purposes-10.csv')

In [ ]:
q = p.loc[p['coalesced_purpose_name'].isin(['Rail transport','Air transport','Industrial development','RESCHEDULING AND REFINANCING','Power generation/non-renewable sources'])]
q